In [1]:
import os
import pandas as pd
import polars as pl
import numpy as np
from prophet import Prophet
from datetime import timedelta
import kaggle_evaluation.mitsui_inference_server
from warnings import filterwarnings
filterwarnings("ignore")

In [2]:
train_labels_df = pd.read_csv('/kaggle/input/mitsui-commodity-prediction-challenge/train_labels.csv')
lagged_test_lab_4_df = pd.read_csv('/kaggle/input/mitsui-commodity-prediction-challenge/lagged_test_labels/test_labels_lag_4.csv')

In [3]:
train_labels_df.tail(20)

,date_id,target_0,target_1,target_2,target_3,target_4,target_5,target_6,target_7,target_8,...,target_414,target_415,target_416,target_417,target_418,target_419,target_420,target_421,target_422,target_423
1941,1941,0.000078,-0.003507,0.020287,0.014108,-0.009511,0.000911,-0.003814,-0.023056,-0.008897,...,NaN,-0.011525,NaN,0.022113,0.015484,0.002498,NaN,NaN,0.020213,NaN
1942,1942,0.004502,0.005992,-0.007980,-0.007661,0.007018,0.002437,0.002254,0.012562,0.002598,...,0.011833,-0.014624,-0.009990,0.024125,0.015996,0.005752,0.006341,0.010535,0.015526,-0.058521
1943,1943,0.005253,-0.003070,-0.003318,-0.003200,-0.013299,-0.040109,0.007924,-0.008450,-0.002596,...,0.024074,-0.014354,-0.005876,0.029499,0.014689,0.009475,0.011455,-0.005665,0.027233,-0.026371
1944,1944,NaN,NaN,0.000599,0.003907,-0.003859,0.004915,0.003107,NaN,NaN,...,-0.000145,-0.009604,-0.027801,-0.034384,0.004697,-0.000428,0.001967,-0.020739,-0.024410,-0.006881
1945,1945,NaN,NaN,0.011053,0.008216,-0.002612,0.002031,-0.004354,NaN,NaN,...,NaN,0.003697,NaN,-0.012088,-0.013203,-0.005897,NaN,NaN,-0.019112,NaN
1946,1946,0.002097,0.007676,-0.017297,-0.008476,-0.009235,-0.009344,0.004927,0.013470,-0.008573,...,0.020801,0.007732,-0.023085,0.012203,-0.012438,-0.013108,0.019849,0.000161,0.013699,0.016334
1947,1947,0.005957,-0.006200,-0.024532,-0.004002,0.012056,0.029059,-0.004295,0.006274,0.007338,...,0.015494,0.022658,-0.030251,-0.000618,0.003688,-0.006769,0.014615,0.000281,-0.001010,-0.061193
1948,1948,0.001849,-0.007703,-0.005259,-0.008274,-0.001940,0.012833,-0.010081,0.006885,-0.003008,...,0.035039,0.022234,-0.002396,0.020389,0.016058,-0.009305,0.039110,0.010308,0.016867,-0.056145
1949,1949,-0.005017,-0.006052,0.009829,0.012234,-0.008801,-0.023372,-0.009342,-0.007974,-0.009900,...,0.025953,0.017638,-0.013480,0.013482,0.019225,-0.005730,0.029508,0.021797,0.022270,-0.079864
1950,1950,0.001778,-0.010972,-0.001196,-0.001126,-0.014067,-0.012107,-0.004959,-0.004146,-0.008003,...,0.012926,0.013299,0.005647,-0.000061,-0.009896,-0.005708,0.001499,0.029689,0.003182,-0.068592
1951,1951,-0.005111,0.001610,0.014913,0.007715,-0.006874,-0.006117,0.000946,-0.000467,0.004528,...,0.001466,-0.004595,0.015213,0.009476,-0.035504,-0.019039,-0.004744,0.010071,0.006809,-0.033269
1952,1952,0.003952,-0.013769,-0.006267,-0.006341,-0.001536,0.007310,-0.008654,0.000394,0.003580,...,NaN,-0.006725,0.001344,NaN,-0.050107,-0.017070,NaN,-0.006722,NaN,0.005249
1953,1953,0.005091,-0.006863,-0.006281,-0.009351,0.001811,0.014153,-0.001966,0.002782,0.007354,...,-0.000729,-0.008356,0.003985,0.012376,-0.043938,-0.013157,-0.000704,-0.035360,0.006352,0.006904
1954,1954,-0.000847,0.019426,-0.017823,-0.009563,0.018225,0.008770,-0.001200,0.031789,-0.003682,...,0.009382,-0.012275,0.012132,0.030011,-0.037556,-0.009914,0.005984,-0.022557,0.029302,0.011154
1955,1955,0.002461,-0.000225,0.001229,-0.000627,NaN,NaN,-0.004208,0.007665,NaN,...,-0.006255,0.005842,0.003945,-0.018496,-0.009460,-0.000114,-0.007490,-0.004104,-0.010907,-0.001935
1956,1956,0.002761,-0.004500,-0.001530,-0.003022,NaN,NaN,-0.006263,0.001251,NaN,...,NaN,0.010110,0.009248,NaN,0.009526,0.004318,NaN,0.005344,NaN,-0.041391
1957,1957,0.011424,-0.001036,0.000409,-0.003524,-0.008052,-0.013435,0.013214,-0.008121,0.005308,...,-0.006012,-0.007567,0.021569,0.008000,0.015748,-0.001036,0.001043,0.015982,0.004550,-0.028627
1958,1958,-0.002654,-0.002032,0.001083,0.004975,0.016810,0.020511,-0.003176,-0.002232,0.012985,...,-0.026047,-0.007783,0.005746,-0.020410,0.026720,0.007130,0.004826,-0.002617,-0.033630,-0.007604
1959,1959,0.002124,-0.006335,-0.003885,0.002704,-0.004042,-0.001637,0.000142,-0.010872,-0.002934,...,-0.006359,-0.006478,0.012228,0.013633,0.022029,0.000092,0.016932,-0.000136,-0.006557,0.009290
1960,1960,-0.005013,0.006502,0.004530,0.000608,-0.003953,-0.025734,0.003007,0.001393,-0.010105,...,-0.004566,-0.001608,-0.001808,-0.018113,0.023452,0.011114,0.024685,0.008946,-0.041073,0.044103

In [4]:
lagged_test_lab_4_df.tail(20)

,date_id,target_318,target_319,target_320,target_321,target_322,target_323,target_324,target_325,target_326,...,target_415,target_416,target_417,target_418,target_419,target_420,target_421,target_422,target_423,label_date_id
114,1946,0.000238,-0.003129,0.026804,0.007153,-0.009471,0.007036,-0.024693,NaN,NaN,...,-0.011525,NaN,0.022113,0.015484,0.002498,NaN,NaN,0.020213,NaN,1941
115,1947,0.001972,-0.011639,0.014014,0.001262,-0.008931,0.009839,-0.029463,-0.041240,-0.024819,...,-0.014624,-0.009990,0.024125,0.015996,0.005752,0.006341,0.010535,0.015526,-0.058521,1942
116,1948,0.002845,-0.015907,0.029452,0.000447,-0.011604,0.021014,-0.042059,-0.033730,-0.033146,...,-0.014354,-0.005876,0.029499,0.014689,0.009475,0.011455,-0.005665,0.027233,-0.026371,1943
117,1949,-0.000272,-0.002996,0.003296,-0.000355,0.000615,0.029206,0.026307,-0.055779,-0.017963,...,-0.009604,-0.027801,-0.034384,0.004697,-0.000428,0.001967,-0.020739,-0.024410,-0.006881,1944
118,1950,0.007469,-0.000735,-0.010804,-0.012536,0.013803,0.009696,0.022044,NaN,NaN,...,0.003697,NaN,-0.012088,-0.013203,-0.005897,NaN,NaN,-0.019112,NaN,1945
119,1951,0.002181,0.009217,-0.000598,-0.008518,0.018791,0.009950,0.000658,-0.087741,-0.025655,...,0.007732,-0.023085,0.012203,-0.012438,-0.013108,0.019849,0.000161,0.013699,0.016334,1946
120,1952,0.000521,0.001797,0.011584,-0.001168,0.028677,-0.008687,0.005245,-0.049585,-0.025784,...,0.022658,-0.030251,-0.000618,0.003688,-0.006769,0.014615,0.000281,-0.001010,-0.061193,1947
121,1953,-0.004877,-0.001305,0.042231,0.010549,0.023436,-0.031174,-0.018215,-0.018680,-0.047710,...,0.022234,-0.002396,0.020389,0.016058,-0.009305,0.039110,0.010308,0.016867,-0.056145,1948
122,1954,-0.011648,0.000076,0.043761,0.012482,0.022009,-0.026806,-0.021805,0.019791,-0.032400,...,0.017638,-0.013480,0.013482,0.019225,-0.005730,0.029508,0.021797,0.022270,-0.079864,1949
123,1955,-0.008895,-0.000755,0.011564,-0.009103,0.014634,-0.024905,-0.005864,-0.089193,-0.010601,...,0.013299,0.005647,-0.000061,-0.009896,-0.005708,0.001499,0.029689,0.003182,-0.068592,1950
124,1956,-0.000959,0.015323,-0.029165,-0.017539,0.010875,-0.012957,0.006577,-0.066367,-0.011059,...,-0.004595,0.015213,0.009476,-0.035504,-0.019039,-0.004744,0.010071,0.006809,-0.033269,1951
125,1957,0.000690,0.024565,NaN,-0.025881,0.016029,-0.012769,NaN,-0.087745,NaN,...,-0.006725,0.001344,NaN,-0.050107,-0.017070,NaN,-0.006722,NaN,0.005249,1952
126,1958,0.008944,0.021998,-0.045457,-0.022562,0.013638,-0.011796,0.015948,-0.150088,0.005195,...,-0.008356,0.003985,0.012376,-0.043938,-0.013157,-0.000704,-0.035360,0.006352,0.006904,1953
127,1959,0.004446,0.023477,-0.029768,-0.016735,-0.001542,0.002521,-0.005814,-0.010014,0.040202,...,-0.012275,0.012132,0.030011,-0.037556,-0.009914,0.005984,-0.022557,0.029302,0.011154,1954
128,1960,-0.004855,0.011488,-0.013815,-0.002198,0.000434,-0.003823,0.020465,-0.082044,0.068905,...,0.005842,0.003945,-0.018496,-0.009460,-0.000114,-0.007490,-0.004104,-0.010907,-0.001935,1955
129,1961,-0.004312,0.000147,NaN,0.001133,-0.003917,0.008973,NaN,-0.082213,NaN,...,0.010110,0.009248,NaN,0.009526,0.004318,NaN,0.005344,NaN,-0.041391,1956
130,1962,0.000969,-0.011177,0.004000,0.004764,-0.013187,0.015814,-0.015532,0.110290,0.028493,...,-0.007567,0.021569,0.008000,0.015748,-0.001036,0.001043,0.015982,0.004550,-0.028627,1957
131,1963,0.008974,-0.026286,-0.000767,0.002805,-0.009655,0.005775,0.009684,0.088034,-0.013834,...,-0.007783,0.005746,-0.020410,0.026720,0.007130,0.004826,-0.002617,-0.033630,-0.007604,1958
132,1964,0.010769,-0.028300,0.017418,0.003077,-0.002336,0.003042,-0.016383,0.185251,-0.030959,...,-0.006478,0.012228,0.013633,0.022029,0.000092,0.016932,-0.000136,-0.006557,0.009290,1959
133,1965,0.011914,-0.039028,0.019687,-0.004549,-0.005279,-0.005478,0.007071,0.188582,-0.024719,...,-0.001608,-0.001808,-0.018113,0.023452,0.011114,0.024685,0.008946,-0.041073,0.044103,1960

In [5]:
lagged_test_lab_4_df.head(10)

,date_id,target_318,target_319,target_320,target_321,target_322,target_323,target_324,target_325,target_326,...,target_415,target_416,target_417,target_418,target_419,target_420,target_421,target_422,target_423,label_date_id
0,1832,0.001082,-0.020023,0.064526,0.028037,0.004506,-0.023554,-0.029856,NaN,NaN,...,0.019701,NaN,-0.027030,0.043602,0.027982,NaN,NaN,0.002177,NaN,1827
1,1833,-0.001296,-0.015281,0.041474,0.009498,-0.005352,0.009397,-0.027311,0.046440,-0.009329,...,0.012081,-0.020068,0.002858,0.019154,0.019018,0.003875,-0.035202,0.011246,0.099241,1828
2,1834,-0.002375,-0.021250,0.041091,0.020435,-0.007740,0.010090,-0.018724,0.033513,0.018609,...,0.016166,-0.028919,-0.007297,0.033262,0.023174,-0.028512,-0.017900,-0.002096,0.121451,1829
3,1835,-0.001846,0.000320,0.016153,0.021035,-0.007409,0.023807,-0.008369,0.045870,0.010528,...,-0.007742,-0.018436,0.004691,0.013311,0.000589,-0.014500,-0.046444,0.009058,0.109246,1830
4,1836,-0.000929,-0.004576,0.004014,0.006592,-0.020097,0.030620,-0.009754,0.050258,0.017386,...,-0.018850,-0.025373,0.031197,0.005873,-0.005650,-0.022926,-0.027990,0.011267,0.091318,1831
5,1837,0.005104,-0.008375,0.041446,0.031493,-0.003528,0.005438,-0.030237,0.053343,0.001698,...,-0.005291,-0.026959,0.025416,0.036183,0.000457,0.012325,0.023296,0.022195,-0.045001,1832
6,1838,0.002868,0.016572,0.005648,0.010829,0.014545,-0.007490,0.003335,0.070443,-0.023820,...,-0.011752,-0.006096,0.024564,-0.014669,-0.026384,0.049811,-0.022768,0.014820,0.036332,1833
7,1839,0.008355,-0.001507,0.009344,-0.001917,0.002014,-0.004223,-0.002697,0.049877,-0.015616,...,-0.007847,-0.023073,0.019207,-0.007262,-0.003535,0.045942,0.006377,0.007368,0.004076,1834
8,1840,0.008006,-0.012012,0.028759,0.000839,-0.021888,0.005742,-0.005277,0.087626,-0.023915,...,-0.008596,-0.011148,0.013248,0.006783,0.012370,0.059634,0.012869,0.001956,0.011147,1835
9,1841,0.007025,0.002567,-0.017011,-0.017748,-0.010468,-0.004882,0.026783,0.083687,0.005502,...,-0.013517,0.006281,-0.003193,-0.020847,-0.000352,0.030961,0.006029,-0.020107,0.040021,1836

In [6]:
1965-1832

133

In [7]:
365*5.383561643835616

1965.0

In [8]:
round(365*0.383561643835616)

140

In [9]:
import os
import pandas as pd
import polars as pl
import numpy as np
from prophet import Prophet
from datetime import timedelta
import kaggle_evaluation.mitsui_inference_server
from warnings import filterwarnings
filterwarnings("ignore")


# ========================
# CONSTANTS
# ========================
NUM_TARGET_COLUMNS = 424
PROPHET_WEIGHT = 0.05
PROPHET_TRAINING_DAYS = 365

# ========================
# LOAD STATIC TRAIN DATA
# ========================
train_labels = pd.read_csv("/kaggle/input/mitsui-commodity-prediction-challenge/train_labels.csv")
test_labels_lag_1_df = pd.read_csv('/kaggle/input/mitsui-commodity-prediction-challenge/lagged_test_labels/test_labels_lag_1.csv')
sel_cols = [col for col in train_labels.columns if col.startswith("target_")]
print(len(sel_cols))
train_labels["date_id"] = train_labels["date_id"].astype(np.uint16)
base_date = pd.Timestamp("2020-01-01")
train_labels["ds"] = base_date + pd.to_timedelta(train_labels["date_id"], unit="D")

# Compute missing values per target
missing_pct = train_labels[sel_cols].isnull().mean()

# ========================
# PRE-TRAIN PROPHET MODELS
# ========================
prophet_models = {}
targets_to_model = train_labels[sel_cols].columns.values

for target in targets_to_model:
    df_prophet = train_labels[["ds", target]].ffill().bfill().rename(columns={target: "y"})
    # df_prophet = df_prophet.head(len(train_labels)-146)
    # model = Prophet(yearly_seasonality=False, weekly_seasonality=True, daily_seasonality=False)
    model = Prophet(yearly_seasonality=True, weekly_seasonality=True, daily_seasonality=False)
    model.fit(df_prophet)
    prophet_models[target] = model

print(prophet_models)

424

13:21:12 - cmdstanpy - INFO - Chain [1] start processing
13:21:12 - cmdstanpy - INFO - Chain [1] done processing
13:21:12 - cmdstanpy - INFO - Chain [1] start processing
13:21:12 - cmdstanpy - INFO - Chain [1] done processing
13:21:12 - cmdstanpy - INFO - Chain [1] start processing
13:21:12 - cmdstanpy - INFO - Chain [1] done processing
13:21:12 - cmdstanpy - INFO - Chain [1] start processing
13:21:12 - cmdstanpy - INFO - Chain [1] done processing
13:21:12 - cmdstanpy - INFO - Chain [1] start processing
13:21:13 - cmdstanpy - INFO - Chain [1] done processing
13:21:13 - cmdstanpy - INFO - Chain [1] start processing
13:21:13 - cmdstanpy - INFO - Chain [1] done processing
13:21:13 - cmdstanpy - INFO - Chain [1] start processing
13:21:13 - cmdstanpy - INFO - Chain [1] done processing
13:21:13 - cmdstanpy - INFO - Chain [1] start processing
13:21:13 - cmdstanpy - INFO - Chain [1] done processing
13:21:13 - cmdstanpy - INFO - Chain [1] start processing
13:21:13 - cmdstanpy - INFO - Chain [1] done processing
13:21:13 - cmdstanpy - INFO - Chain [1] start processing
13:21:13 - cmdstanpy - INFO - Chain [1] done processing
13:21:14 - cmdstanpy - INFO - Chain [1] start processing
13:21:14 - cmdstanpy - INFO - Chain [1] done processing
13:21:14 - cmdstanpy - INFO - Chain [1] start processing
13:21:14 - cmdstanpy - INFO - Chain [1] done processing
13:21:14 - cmdstanpy - INFO - Chain [1] start processing
13:21:14 - cmdstanpy - INFO - Chain [1] done processing
13:21:14 - cmdstanpy - INFO - Chain [1] start processing
13:21:14 - cmdstanpy - INFO - Chain [1] done processing
13:21:14 - cmdstanpy - INFO - Chain [1] start processing
13:21:14 - cmdstanpy - INFO - Chain [1] done processing
13:21:14 - cmdstanpy - INFO - Chain [1] start processing
13:21:14 - cmdstanpy - INFO - Chain [1] done processing
13:21:15 - cmdstanpy - INFO - Chain [1] start processing
13:21:15 - cmdstanpy - INFO - Chain [1] done processing
13:21:15 - cmdstanpy - INFO - Chain [1] start processing
13:21:15 - cmdstanpy - INFO - Chain [1] done processing
13:21:15 - cmdstanpy - INFO - Chain [1] start processing
13:21:15 - cmdstanpy - INFO - Chain [1] done processing
13:21:15 - cmdstanpy - INFO - Chain [1] start processing
13:21:15 - cmdstanpy - INFO - Chain [1] done processing
13:21:15 - cmdstanpy - INFO - Chain [1] start processing
13:21:15 - cmdstanpy - INFO - Chain [1] done processing
13:21:16 - cmdstanpy - INFO - Chain [1] start processing
13:21:16 - cmdstanpy - INFO - Chain [1] done processing
13:21:16 - cmdstanpy - INFO - Chain [1] start processing
13:21:16 - cmdstanpy - INFO - Chain [1] done processing
13:21:16 - cmdstanpy - INFO - Chain [1] start processing
13:21:16 - cmdstanpy - INFO - Chain [1] done processing
13:21:16 - cmdstanpy - INFO - Chain [1] start processing
13:21:16 - cmdstanpy - INFO - Chain [1] done processing
13:21:16 - cmdstanpy - INFO - Chain [1] start processing
13:21:16 - cmdstanpy - INFO - Chain [1] done processing
13:21:16 - cmdstanpy - INFO - Chain [1] start processing
13:21:17 - cmdstanpy - INFO - Chain [1] done processing
13:21:17 - cmdstanpy - INFO - Chain [1] start processing
13:21:17 - cmdstanpy - INFO - Chain [1] done processing
13:21:17 - cmdstanpy - INFO - Chain [1] start processing
13:21:17 - cmdstanpy - INFO - Chain [1] done processing
13:21:17 - cmdstanpy - INFO - Chain [1] start processing
13:21:17 - cmdstanpy - INFO - Chain [1] done processing
13:21:17 - cmdstanpy - INFO - Chain [1] start processing
13:21:17 - cmdstanpy - INFO - Chain [1] done processing
13:21:17 - cmdstanpy - INFO - Chain [1] start processing
13:21:17 - cmdstanpy - INFO - Chain [1] done processing
13:21:18 - cmdstanpy - INFO - Chain [1] start processing
13:21:18 - cmdstanpy - INFO - Chain [1] done processing
13:21:18 - cmdstanpy - INFO - Chain [1] start processing
13:21:18 - cmdstanpy - INFO - Chain [1] done processing
13:21:18 - cmdstanpy - INFO - Chain [1] start processing
13:21:18 - cmdstanpy - INFO - Chain [1] done processing
13:21:18 - cmdstanpy - INFO - Chain [1] start processing
13:21:18 - cmdstanpy - INFO - Chain [1] done processing
13:21:18 - cmdstanpy - INFO - Chain [1] start processing
13:21:18 - cmdstanpy - INFO - Chain [1] done processing
13:21:18 - cmdstanpy - INFO - Chain [1] start processing
13:21:19 - cmdstanpy - INFO - Chain [1] done processing
13:21:19 - cmdstanpy - INFO - Chain [1] start processing
13:21:19 - cmdstanpy - INFO - Chain [1] done processing
13:21:19 - cmdstanpy - INFO - Chain [1] start processing
13:21:19 - cmdstanpy - INFO - Chain [1] done processing
13:21:19 - cmdstanpy - INFO - Chain [1] start processing
13:21:19 - cmdstanpy - INFO - Chain [1] done processing
13:21:19 - cmdstanpy - INFO - Chain [1] start processing
13:21:19 - cmdstanpy - INFO - Chain [1] done processing
13:21:19 - cmdstanpy - INFO - Chain [1] start processing
13:21:19 - cmdstanpy - INFO - Chain [1] done processing
13:21:20 - cmdstanpy - INFO - Chain [1] start processing
13:21:20 - cmdstanpy - INFO - Chain [1] done processing
13:21:20 - cmdstanpy - INFO - Chain [1] start processing
13:21:20 - cmdstanpy - INFO - Chain [1] done processing
13:21:20 - cmdstanpy - INFO - Chain [1] start processing
13:21:20 - cmdstanpy - INFO - Chain [1] done processing
13:21:20 - cmdstanpy - INFO - Chain [1] start processing
13:21:20 - cmdstanpy - INFO - Chain [1] done processing
13:21:20 - cmdstanpy - INFO - Chain [1] start processing
13:21:20 - cmdstanpy - INFO - Chain [1] done processing
13:21:21 - cmdstanpy - INFO - Chain [1] start processing
13:21:21 - cmdstanpy - INFO - Chain [1] done processing
13:21:21 - cmdstanpy - INFO - Chain [1] start processing
13:21:21 - cmdstanpy - INFO - Chain [1] done processing
13:21:21 - cmdstanpy - INFO - Chain [1] start processing
13:21:21 - cmdstanpy - INFO - Chain [1] done processing
13:21:21 - cmdstanpy - INFO - Chain [1] start processing
13:21:21 - cmdstanpy - INFO - Chain [1] done processing
13:21:21 - cmdstanpy - INFO - Chain [1] start processing
13:21:21 - cmdstanpy - INFO - Chain [1] done processing
13:21:21 - cmdstanpy - INFO - Chain [1] start processing
13:21:22 - cmdstanpy - INFO - Chain [1] done processing
13:21:22 - cmdstanpy - INFO - Chain [1] start processing
13:21:22 - cmdstanpy - INFO - Chain [1] done processing
13:21:22 - cmdstanpy - INFO - Chain [1] start processing
13:21:22 - cmdstanpy - INFO - Chain [1] done processing
13:21:22 - cmdstanpy - INFO - Chain [1] start processing
13:21:22 - cmdstanpy - INFO - Chain [1] done processing
13:21:22 - cmdstanpy - INFO - Chain [1] start processing
13:21:22 - cmdstanpy - INFO - Chain [1] done processing
13:21:22 - cmdstanpy - INFO - Chain [1] start processing
13:21:22 - cmdstanpy - INFO - Chain [1] done processing
13:21:22 - cmdstanpy - INFO - Chain [1] start processing
13:21:23 - cmdstanpy - INFO - Chain [1] done processing
13:21:23 - cmdstanpy - INFO - Chain [1] start processing
13:21:23 - cmdstanpy - INFO - Chain [1] done processing
13:21:23 - cmdstanpy - INFO - Chain [1] start processing
13:21:23 - cmdstanpy - INFO - Chain [1] done processing
13:21:23 - cmdstanpy - INFO - Chain [1] start processing
13:21:23 - cmdstanpy - INFO - Chain [1] done processing
13:21:23 - cmdstanpy - INFO - Chain [1] start processing
13:21:23 - cmdstanpy - INFO - Chain [1] done processing
13:21:23 - cmdstanpy - INFO - Chain [1] start processing
13:21:24 - cmdstanpy - INFO - Chain [1] done processing
13:21:24 - cmdstanpy - INFO - Chain [1] start processing
13:21:24 - cmdstanpy - INFO - Chain [1] done processing
13:21:24 - cmdstanpy - INFO - Chain [1] start processing
13:21:24 - cmdstanpy - INFO - Chain [1] done processing
13:21:24 - cmdstanpy - INFO - Chain [1] start processing
13:21:24 - cmdstanpy - INFO - Chain [1] done processing
13:21:24 - cmdstanpy - INFO - Chain [1] start processing
13:21:24 - cmdstanpy - INFO - Chain [1] done processing
13:21:24 - cmdstanpy - INFO - Chain [1] start processing
13:21:25 - cmdstanpy - INFO - Chain [1] done processing
13:21:25 - cmdstanpy - INFO - Chain [1] start processing
13:21:25 - cmdstanpy - INFO - Chain [1] done processing
13:21:25 - cmdstanpy - INFO - Chain [1] start processing
13:21:25 - cmdstanpy - INFO - Chain [1] done processing
13:21:25 - cmdstanpy - INFO - Chain [1] start processing
13:21:25 - cmdstanpy - INFO - Chain [1] done processing
13:21:25 - cmdstanpy - INFO - Chain [1] start processing
13:21:25 - cmdstanpy - INFO - Chain [1] done processing
13:21:26 - cmdstanpy - INFO - Chain [1] start processing
13:21:26 - cmdstanpy - INFO - Chain [1] done processing
13:21:26 - cmdstanpy - INFO - Chain [1] start processing
13:21:26 - cmdstanpy - INFO - Chain [1] done processing
13:21:26 - cmdstanpy - INFO - Chain [1] start processing
13:21:26 - cmdstanpy - INFO - Chain [1] done processing
13:21:26 - cmdstanpy - INFO - Chain [1] start processing
13:21:26 - cmdstanpy - INFO - Chain [1] done processing
13:21:26 - cmdstanpy - INFO - Chain [1] start processing
13:21:26 - cmdstanpy - INFO - Chain [1] done processing
13:21:26 - cmdstanpy - INFO - Chain [1] start processing
13:21:26 - cmdstanpy - INFO - Chain [1] done processing
13:21:27 - cmdstanpy - INFO - Chain [1] start processing
13:21:27 - cmdstanpy - INFO - Chain [1] done processing
13:21:27 - cmdstanpy - INFO - Chain [1] start processing
13:21:27 - cmdstanpy - INFO - Chain [1] done processing
13:21:27 - cmdstanpy - INFO - Chain [1] start processing
13:21:27 - cmdstanpy - INFO - Chain [1] done processing
13:21:27 - cmdstanpy - INFO - Chain [1] start processing
13:21:27 - cmdstanpy - INFO - Chain [1] done processing
13:21:27 - cmdstanpy - INFO - Chain [1] start processing
13:21:27 - cmdstanpy - INFO - Chain [1] done processing
13:21:27 - cmdstanpy - INFO - Chain [1] start processing
13:21:28 - cmdstanpy - INFO - Chain [1] done processing
13:21:28 - cmdstanpy - INFO - Chain [1] start processing
13:21:28 - cmdstanpy - INFO - Chain [1] done processing
13:21:28 - cmdstanpy - INFO - Chain [1] start processing
13:21:28 - cmdstanpy - INFO - Chain [1] done processing
13:21:28 - cmdstanpy - INFO - Chain [1] start processing
13:21:28 - cmdstanpy - INFO - Chain [1] done processing
13:21:28 - cmdstanpy - INFO - Chain [1] start processing
13:21:28 - cmdstanpy - INFO - Chain [1] done processing
13:21:28 - cmdstanpy - INFO - Chain [1] start processing
13:21:28 - cmdstanpy - INFO - Chain [1] done processing
13:21:29 - cmdstanpy - INFO - Chain [1] start processing
13:21:29 - cmdstanpy - INFO - Chain [1] done processing
13:21:29 - cmdstanpy - INFO - Chain [1] start processing
13:21:29 - cmdstanpy - INFO - Chain [1] done processing
13:21:29 - cmdstanpy - INFO - Chain [1] start processing
13:21:29 - cmdstanpy - INFO - Chain [1] done processing
13:21:29 - cmdstanpy - INFO - Chain [1] start processing
13:21:29 - cmdstanpy - INFO - Chain [1] done processing
13:21:29 - cmdstanpy - INFO - Chain [1] start processing
13:21:30 - cmdstanpy - INFO - Chain [1] done processing
13:21:30 - cmdstanpy - INFO - Chain [1] start processing
13:21:30 - cmdstanpy - INFO - Chain [1] done processing
13:21:30 - cmdstanpy - INFO - Chain [1] start processing
13:21:30 - cmdstanpy - INFO - Chain [1] done processing
13:21:30 - cmdstanpy - INFO - Chain [1] start processing
13:21:30 - cmdstanpy - INFO - Chain [1] done processing
13:21:30 - cmdstanpy - INFO - Chain [1] start processing
13:21:30 - cmdstanpy - INFO - Chain [1] done processing
13:21:30 - cmdstanpy - INFO - Chain [1] start processing
13:21:30 - cmdstanpy - INFO - Chain [1] done processing
13:21:31 - cmdstanpy - INFO - Chain [1] start processing
13:21:31 - cmdstanpy - INFO - Chain [1] done processing
13:21:31 - cmdstanpy - INFO - Chain [1] start processing
13:21:31 - cmdstanpy - INFO - Chain [1] done processing
13:21:31 - cmdstanpy - INFO - Chain [1] start processing
13:21:31 - cmdstanpy - INFO - Chain [1] done processing
13:21:31 - cmdstanpy - INFO - Chain [1] start processing
13:21:31 - cmdstanpy - INFO - Chain [1] done processing
13:21:31 - cmdstanpy - INFO - Chain [1] start processing
13:21:31 - cmdstanpy - INFO - Chain [1] done processing
13:21:31 - cmdstanpy - INFO - Chain [1] start processing
13:21:32 - cmdstanpy - INFO - Chain [1] done processing
13:21:32 - cmdstanpy - INFO - Chain [1] start processing
13:21:32 - cmdstanpy - INFO - Chain [1] done processing
13:21:32 - cmdstanpy - INFO - Chain [1] start processing
13:21:32 - cmdstanpy - INFO - Chain [1] done processing
13:21:32 - cmdstanpy - INFO - Chain [1] start processing
13:21:32 - cmdstanpy - INFO - Chain [1] done processing
13:21:32 - cmdstanpy - INFO - Chain [1] start processing
13:21:32 - cmdstanpy - INFO - Chain [1] done processing
13:21:32 - cmdstanpy - INFO - Chain [1] start processing
13:21:33 - cmdstanpy - INFO - Chain [1] done processing
13:21:33 - cmdstanpy - INFO - Chain [1] start processing
13:21:33 - cmdstanpy - INFO - Chain [1] done processing
13:21:33 - cmdstanpy - INFO - Chain [1] start processing
13:21:33 - cmdstanpy - INFO - Chain [1] done processing
13:21:33 - cmdstanpy - INFO - Chain [1] start processing
13:21:33 - cmdstanpy - INFO - Chain [1] done processing
13:21:33 - cmdstanpy - INFO - Chain [1] start processing
13:21:33 - cmdstanpy - INFO - Chain [1] done processing
13:21:33 - cmdstanpy - INFO - Chain [1] start processing
13:21:33 - cmdstanpy - INFO - Chain [1] done processing
13:21:33 - cmdstanpy - INFO - Chain [1] start processing
13:21:34 - cmdstanpy - INFO - Chain [1] done processing
13:21:34 - cmdstanpy - INFO - Chain [1] start processing
13:21:34 - cmdstanpy - INFO - Chain [1] done processing
13:21:34 - cmdstanpy - INFO - Chain [1] start processing
13:21:34 - cmdstanpy - INFO - Chain [1] done processing
13:21:34 - cmdstanpy - INFO - Chain [1] start processing
13:21:34 - cmdstanpy - INFO - Chain [1] done processing
13:21:34 - cmdstanpy - INFO - Chain [1] start processing
13:21:34 - cmdstanpy - INFO - Chain [1] done processing
13:21:34 - cmdstanpy - INFO - Chain [1] start processing
13:21:35 - cmdstanpy - INFO - Chain [1] done processing
13:21:35 - cmdstanpy - INFO - Chain [1] start processing
13:21:35 - cmdstanpy - INFO - Chain [1] done processing
13:21:35 - cmdstanpy - INFO - Chain [1] start processing
13:21:35 - cmdstanpy - INFO - Chain [1] done processing
13:21:35 - cmdstanpy - INFO - Chain [1] start processing
13:21:35 - cmdstanpy - INFO - Chain [1] done processing
13:21:35 - cmdstanpy - INFO - Chain [1] start processing
13:21:35 - cmdstanpy - INFO - Chain [1] done processing
13:21:35 - cmdstanpy - INFO - Chain [1] start processing
13:21:35 - cmdstanpy - INFO - Chain [1] done processing
13:21:36 - cmdstanpy - INFO - Chain [1] start processing
13:21:36 - cmdstanpy - INFO - Chain [1] done processing
13:21:36 - cmdstanpy - INFO - Chain [1] start processing
13:21:36 - cmdstanpy - INFO - Chain [1] done processing
13:21:36 - cmdstanpy - INFO - Chain [1] start processing
13:21:36 - cmdstanpy - INFO - Chain [1] done processing
13:21:36 - cmdstanpy - INFO - Chain [1] start processing
13:21:36 - cmdstanpy - INFO - Chain [1] done processing
13:21:36 - cmdstanpy - INFO - Chain [1] start processing
13:21:36 - cmdstanpy - INFO - Chain [1] done processing
13:21:36 - cmdstanpy - INFO - Chain [1] start processing
13:21:37 - cmdstanpy - INFO - Chain [1] done processing
13:21:37 - cmdstanpy - INFO - Chain [1] start processing
13:21:37 - cmdstanpy - INFO - Chain [1] done processing
13:21:37 - cmdstanpy - INFO - Chain [1] start processing
13:21:37 - cmdstanpy - INFO - Chain [1] done processing
13:21:37 - cmdstanpy - INFO - Chain [1] start processing
13:21:37 - cmdstanpy - INFO - Chain [1] done processing
13:21:37 - cmdstanpy - INFO - Chain [1] start processing
13:21:37 - cmdstanpy - INFO - Chain [1] done processing
13:21:37 - cmdstanpy - INFO - Chain [1] start processing
13:21:37 - cmdstanpy - INFO - Chain [1] done processing
13:21:38 - cmdstanpy - INFO - Chain [1] start processing
13:21:38 - cmdstanpy - INFO - Chain [1] done processing
13:21:38 - cmdstanpy - INFO - Chain [1] start processing
13:21:38 - cmdstanpy - INFO - Chain [1] done processing
13:21:38 - cmdstanpy - INFO - Chain [1] start processing
13:21:38 - cmdstanpy - INFO - Chain [1] done processing
13:21:38 - cmdstanpy - INFO - Chain [1] start processing
13:21:38 - cmdstanpy - INFO - Chain [1] done processing
13:21:38 - cmdstanpy - INFO - Chain [1] start processing
13:21:38 - cmdstanpy - INFO - Chain [1] done processing
13:21:38 - cmdstanpy - INFO - Chain [1] start processing
13:21:39 - cmdstanpy - INFO - Chain [1] done processing
13:21:39 - cmdstanpy - INFO - Chain [1] start processing
13:21:39 - cmdstanpy - INFO - Chain [1] done processing
13:21:39 - cmdstanpy - INFO - Chain [1] start processing
13:21:39 - cmdstanpy - INFO - Chain [1] done processing
13:21:39 - cmdstanpy - INFO - Chain [1] start processing
13:21:39 - cmdstanpy - INFO - Chain [1] done processing
13:21:39 - cmdstanpy - INFO - Chain [1] start processing
13:21:39 - cmdstanpy - INFO - Chain [1] done processing
13:21:39 - cmdstanpy - INFO - Chain [1] start processing
13:21:39 - cmdstanpy - INFO - Chain [1] done processing
13:21:40 - cmdstanpy - INFO - Chain [1] start processing
13:21:40 - cmdstanpy - INFO - Chain [1] done processing
13:21:40 - cmdstanpy - INFO - Chain [1] start processing
13:21:40 - cmdstanpy - INFO - Chain [1] done processing
13:21:40 - cmdstanpy - INFO - Chain [1] start processing
13:21:40 - cmdstanpy - INFO - Chain [1] done processing
13:21:40 - cmdstanpy - INFO - Chain [1] start processing
13:21:40 - cmdstanpy - INFO - Chain [1] done processing
13:21:40 - cmdstanpy - INFO - Chain [1] start processing
13:21:41 - cmdstanpy - INFO - Chain [1] done processing
13:21:41 - cmdstanpy - INFO - Chain [1] start processing
13:21:41 - cmdstanpy - INFO - Chain [1] done processing
13:21:41 - cmdstanpy - INFO - Chain [1] start processing
13:21:41 - cmdstanpy - INFO - Chain [1] done processing
13:21:41 - cmdstanpy - INFO - Chain [1] start processing
13:21:41 - cmdstanpy - INFO - Chain [1] done processing
13:21:41 - cmdstanpy - INFO - Chain [1] start processing
13:21:41 - cmdstanpy - INFO - Chain [1] done processing
13:21:41 - cmdstanpy - INFO - Chain [1] start processing
13:21:42 - cmdstanpy - INFO - Chain [1] done processing
13:21:42 - cmdstanpy - INFO - Chain [1] start processing
13:21:42 - cmdstanpy - INFO - Chain [1] done processing
13:21:42 - cmdstanpy - INFO - Chain [1] start processing
13:21:42 - cmdstanpy - INFO - Chain [1] done processing
13:21:42 - cmdstanpy - INFO - Chain [1] start processing
13:21:42 - cmdstanpy - INFO - Chain [1] done processing
13:21:42 - cmdstanpy - INFO - Chain [1] start processing
13:21:42 - cmdstanpy - INFO - Chain [1] done processing
13:21:43 - cmdstanpy - INFO - Chain [1] start processing
13:21:43 - cmdstanpy - INFO - Chain [1] done processing
13:21:43 - cmdstanpy - INFO - Chain [1] start processing
13:21:43 - cmdstanpy - INFO - Chain [1] done processing
13:21:43 - cmdstanpy - INFO - Chain [1] start processing
13:21:43 - cmdstanpy - INFO - Chain [1] done processing
13:21:43 - cmdstanpy - INFO - Chain [1] start processing
13:21:43 - cmdstanpy - INFO - Chain [1] done processing
13:21:43 - cmdstanpy - INFO - Chain [1] start processing
13:21:43 - cmdstanpy - INFO - Chain [1] done processing
13:21:43 - cmdstanpy - INFO - Chain [1] start processing
13:21:44 - cmdstanpy - INFO - Chain [1] done processing
13:21:44 - cmdstanpy - INFO - Chain [1] start processing
13:21:44 - cmdstanpy - INFO - Chain [1] done processing
13:21:44 - cmdstanpy - INFO - Chain [1] start processing
13:21:44 - cmdstanpy - INFO - Chain [1] done processing
13:21:44 - cmdstanpy - INFO - Chain [1] start processing
13:21:44 - cmdstanpy - INFO - Chain [1] done processing
13:21:44 - cmdstanpy - INFO - Chain [1] start processing
13:21:44 - cmdstanpy - INFO - Chain [1] done processing
13:21:45 - cmdstanpy - INFO - Chain [1] start processing
13:21:45 - cmdstanpy - INFO - Chain [1] done processing
13:21:45 - cmdstanpy - INFO - Chain [1] start processing
13:21:45 - cmdstanpy - INFO - Chain [1] done processing
13:21:45 - cmdstanpy - INFO - Chain [1] start processing

{'target_0': <prophet.forecaster.Prophet object at 0x7cc564ebb290>, 'target_1': <prophet.forecaster.Prophet object at 0x7cc564ef11d0>, 'target_2': <prophet.forecaster.Prophet object at 0x7cc55fda8390>, 'target_3': <prophet.forecaster.Prophet object at 0x7cc564f4af90>, 'target_4': <prophet.forecaster.Prophet object at 0x7cc564f35790>, 'target_5': <prophet.forecaster.Prophet object at 0x7cc55fab25d0>, 'target_6': <prophet.forecaster.Prophet object at 0x7cc55fa8a750>, 'target_7': <prophet.forecaster.Prophet object at 0x7cc55fab23d0>, 'target_8': <prophet.forecaster.Prophet object at 0x7cc55f70c290>, 'target_9': <prophet.forecaster.Prophet object at 0x7cc55f9a2990>, 'target_10': <prophet.forecaster.Prophet object at 0x7cc55f70df90>, 'target_11': <prophet.forecaster.Prophet object at 0x7cc55f8e6250>, 'target_12': <prophet.forecaster.Prophet object at 0x7cc55f8e6d10>, 'target_13': <prophet.forecaster.Prophet object at 0x7cc55f92ee90>, 'target_14': <prophet.forecaster.Prophet object at 0x7cc55faa2010>, 'target_15': <prophet.forecaster.Prophet object at 0x7cc55faa34d0>, 'target_16': <prophet.forecaster.Prophet object at 0x7cc564ebd390>, 'target_17': <prophet.forecaster.Prophet object at 0x7cc55f9292d0>, 'target_18': <prophet.forecaster.Prophet object at 0x7cc55f6887d0>, 'target_19': <prophet.forecaster.Prophet object at 0x7cc55fa894d0>, 'target_20': <prophet.forecaster.Prophet object at 0x7cc55f688850>, 'target_21': <prophet.forecaster.Prophet object at 0x7cc55f662890>, 'target_22': <prophet.forecaster.Prophet object at 0x7cc55fa92010>, 'target_23': <prophet.forecaster.Prophet object at 0x7cc55f9b7dd0>, 'target_24': <prophet.forecaster.Prophet object at 0x7cc55f656150>, 'target_25': <prophet.forecaster.Prophet object at 0x7cc55f86b710>, 'target_26': <prophet.forecaster.Prophet object at 0x7cc55f682650>, 'target_27': <prophet.forecaster.Prophet object at 0x7cc55f658250>, 'target_28': <prophet.forecaster.Prophet object at 0x7cc55f51bd90>, 'target_29': <prophet.forecaster.Prophet object at 0x7cc55f60be50>, 'target_30': <prophet.forecaster.Prophet object at 0x7cc55f60ae90>, 'target_31': <prophet.forecaster.Prophet object at 0x7cc55f9fef90>, 'target_32': <prophet.forecaster.Prophet object at 0x7cc564ed8490>, 'target_33': <prophet.forecaster.Prophet object at 0x7cc55f92d5d0>, 'target_34': <prophet.forecaster.Prophet object at 0x7cc55f536ed0>, 'target_35': <prophet.forecaster.Prophet object at 0x7cc55fa78310>, 'target_36': <prophet.forecaster.Prophet object at 0x7cc55fa79d50>, 'target_37': <prophet.forecaster.Prophet object at 0x7cc55f9b6290>, 'target_38': <prophet.forecaster.Prophet object at 0x7cc55f5b9910>, 'target_39': <prophet.forecaster.Prophet object at 0x7cc55f447c90>, 'target_40': <prophet.forecaster.Prophet object at 0x7cc55f897750>, 'target_41': <prophet.forecaster.Prophet object at 0x7cc55f447d90>, 'target_42': <prophet.forecaster.Prophet object at 0x7cc55f6e42d0>, 'target_43': <prophet.forecaster.Prophet object at 0x7cc55f6bda50>, 'target_44': <prophet.forecaster.Prophet object at 0x7cc55f61fad0>, 'target_45': <prophet.forecaster.Prophet object at 0x7cc55f663b90>, 'target_46': <prophet.forecaster.Prophet object at 0x7cc55f4b5290>, 'target_47': <prophet.forecaster.Prophet object at 0x7cc55f3adad0>, 'target_48': <prophet.forecaster.Prophet object at 0x7cc55f4b6850>, 'target_49': <prophet.forecaster.Prophet object at 0x7cc55f6bcdd0>, 'target_50': <prophet.forecaster.Prophet object at 0x7cc55f3b8450>, 'target_51': <prophet.forecaster.Prophet object at 0x7cc55f2b3b90>, 'target_52': <prophet.forecaster.Prophet object at 0x7cc55f8e6d50>, 'target_53': <prophet.forecaster.Prophet object at 0x7cc55f356c50>, 'target_54': <prophet.forecaster.Prophet object at 0x7cc55f2df290>, 'target_55': <prophet.forecaster.Prophet object at 0x7cc55f14ff50>, 'target_56': <prophet.forecaster.Prophet object at 0x7cc55f9a1c90>, 'target_57': <prophet.forecaster.Prophet object at 0x7cc55ee16d50>, 'target_58': <prophet.forecaster.Prophet object at 0x7cc55fab0c50>, 'target_59': <prophet.forecaster.Prophet object at 0x7cc55f929190>, 'target_60': <prophet.forecaster.Prophet object at 0x7cc55f03ff50>, 'target_61': <prophet.forecaster.Prophet object at 0x7cc55ee17150>, 'target_62': <prophet.forecaster.Prophet object at 0x7cc55f9b8110>, 'target_63': <prophet.forecaster.Prophet object at 0x7cc55f023990>, 'target_64': <prophet.forecaster.Prophet object at 0x7cc55f777350>, 'target_65': <prophet.forecaster.Prophet object at 0x7cc55f237550>, 'target_66': <prophet.forecaster.Prophet object at 0x7cc55f589c50>, 'target_67': <prophet.forecaster.Prophet object at 0x7cc55f333950>, 'target_68': <prophet.forecaster.Prophet object at 0x7cc55f8e5890>, 'target_69': <prophet.forecaster.Prophet object at 0x7cc55f19d3d0>, 'target_70': <prophet.forecaster.Prophet object at 0x7cc55f014bd0>, 'target_71': <prophet.forecaster.Prophet object at 0x7cc55f30a310>, 'target_72': <prophet.forecaster.Prophet object at 0x7cc55efe8c10>, 'target_73': <prophet.forecaster.Prophet object at 0x7cc55ef95b90>, 'target_74': <prophet.forecaster.Prophet object at 0x7cc55f2dfd10>, 'target_75': <prophet.forecaster.Prophet object at 0x7cc55f5e0950>, 'target_76': <prophet.forecaster.Prophet object at 0x7cc55f0ea110>, 'target_77': <prophet.forecaster.Prophet object at 0x7cc55f5e25d0>, 'target_78': <prophet.forecaster.Prophet object at 0x7cc55f7c0710>, 'target_79': <prophet.forecaster.Prophet object at 0x7cc55f1c0b90>, 'target_80': <prophet.forecaster.Prophet object at 0x7cc55ef57550>, 'target_81': <prophet.forecaster.Prophet object at 0x7cc55ee7c550>, 'target_82': <prophet.forecaster.Prophet object at 0x7cc55f4c6290>, 'target_83': <prophet.forecaster.Prophet object at 0x7cc55efb6e50>, 'target_84': <prophet.forecaster.Prophet object at 0x7cc55f709b50>, 'target_85': <prophet.forecaster.Prophet object at 0x7cc55f980bd0>, 'target_86': <prophet.forecaster.Prophet object at 0x7cc55eca4390>, 'target_87': <prophet.forecaster.Prophet object at 0x7cc55ed1d4d0>, 'target_88': <prophet.forecaster.Prophet object at 0x7cc55eea3e10>, 'target_89': <prophet.forecaster.Prophet object at 0x7cc55eb0bc90>, 'target_90': <prophet.forecaster.Prophet object at 0x7cc55ed6e490>, 'target_91': <prophet.forecaster.Prophet object at 0x7cc55ec0d490>, 'target_92': <prophet.forecaster.Prophet object at 0x7cc55ee45f90>, 'target_93': <prophet.forecaster.Prophet object at 0x7cc55f4c4d90>, 'target_94': <prophet.forecaster.Prophet object at 0x7cc55ed6ea90>, 'target_95': <prophet.forecaster.Prophet object at 0x7cc55eb74e10>, 'target_96': <prophet.forecaster.Prophet object at 0x7cc55ebc4a10>, 'target_97': <prophet.forecaster.Prophet object at 0x7cc55f2cb390>, 'target_98': <prophet.forecaster.Prophet object at 0x7cc55ea73090>, 'target_99': <prophet.forecaster.Prophet object at 0x7cc55ea72a90>, 'target_100': <prophet.forecaster.Prophet object at 0x7cc55ea53650>, 'target_101': <prophet.forecaster.Prophet object at 0x7cc55e967690>, 'target_102': <prophet.forecaster.Prophet object at 0x7cc55eb9c050>, 'target_103': <prophet.forecaster.Prophet object at 0x7cc55e967d10>, 'target_104': <prophet.forecaster.Prophet object at 0x7cc55f60a390>, 'target_105': <prophet.forecaster.Prophet object at 0x7cc55e923b50>, 'target_106': <prophet.forecaster.Prophet object at 0x7cc55ec6be90>, 'target_107': <prophet.forecaster.Prophet object at 0x7cc55f658f50>, 'target_108': <prophet.forecaster.Prophet object at 0x7cc55f077690>, 'target_109': <prophet.forecaster.Prophet object at 0x7cc55f8cf210>, 'target_110': <prophet.forecaster.Prophet object at 0x7cc595dd14d0>, 'target_111': <prophet.forecaster.Prophet object at 0x7cc55e944e10>, 'target_112': <prophet.forecaster.Prophet object at 0x7cc595db7b50>, 'target_113': <prophet.forecaster.Prophet object at 0x7cc595db7c50>, 'target_114': <prophet.forecaster.Prophet object at 0x7cc55ebeea90>, 'target_115': <prophet.forecaster.Prophet object at 0x7cc55e976ad0>, 'target_116': <prophet.forecaster.Prophet object at 0x7cc595dbddd0>, 'target_117': <prophet.forecaster.Prophet object at 0x7cc55edf3790>, 'target_118': <prophet.forecaster.Prophet object at 0x7cc55f1c00d0>, 'target_119': <prophet.forecaster.Prophet object at 0x7cc55e8ad7d0>, 'target_120': <prophet.forecaster.Prophet object at 0x7cc595d90850>, 'target_121': <prophet.forecaster.Prophet object at 0x7cc55e9b07d0>, 'target_122': <prophet.forecaster.Prophet object at 0x7cc595d92310>, 'target_123': <prophet.forecaster.Prophet object at 0x7cc55f565190>, 'target_124': <prophet.forecaster.Prophet object at 0x7cc55e7fc490>, 'target_125': <prophet.forecaster.Prophet object at 0x7cc55edfc210>, 'target_126': <prophet.forecaster.Prophet object at 0x7cc55e7fce10>, 'target_127': <prophet.forecaster.Prophet object at 0x7cc55e448ed0>, 'target_128': <prophet.forecaster.Prophet object at 0x7cc55e7c63d0>, 'target_129': <prophet.forecaster.Prophet object at 0x7cc55e8d5a50>, 'target_130': <prophet.forecaster.Prophet object at 0x7cc55e6f4190>, 'target_131': <prophet.forecaster.Prophet object at 0x7cc55e7427d0>, 'target_132': <prophet.forecaster.Prophet object at 0x7cc55eaa3ed0>, 'target_133': <prophet.forecaster.Prophet object at 0x7cc55f03ee10>, 'target_134': <prophet.forecaster.Prophet object at 0x7cc55ea53450>, 'target_135': <prophet.forecaster.Prophet object at 0x7cc55ea14d90>, 'target_136': <prophet.forecaster.Prophet object at 0x7cc595e0e150>, 'target_137': <prophet.forecaster.Prophet object at 0x7cc55efe8f10>, 'target_138': <prophet.forecaster.Prophet object at 0x7cc55ec906d0>, 'target_139': <prophet.forecaster.Prophet object at 0x7cc595e3e050>, 'target_140': <prophet.forecaster.Prophet object at 0x7cc55e41fa90>, 'target_141': <prophet.forecaster.Prophet object at 0x7cc55e715190>, 'target_142': <prophet.forecaster.Prophet object at 0x7cc55e8d9350>, 'target_143': <prophet.forecaster.Prophet object at 0x7cc55e8d82d0>, 'target_144': <prophet.forecaster.Prophet object at 0x7cc55e4c2590>, 'target_145': <prophet.forecaster.Prophet object at 0x7cc55e4c0d10>, 'target_146': <prophet.forecaster.Prophet object at 0x7cc55e4b7390>, 'target_147': <prophet.forecaster.Prophet object at 0x7cc55e79a050>, 'target_148': <prophet.forecaster.Prophet object at 0x7cc55ed1ebd0>, 'target_149': <prophet.forecaster.Prophet object at 0x7cc55e5651d0>, 'target_150': <prophet.forecaster.Prophet object at 0x7cc55e4272d0>, 'target_151': <prophet.forecaster.Prophet object at 0x7cc55e4ba250>, 'target_152': <prophet.forecaster.Prophet object at 0x7cc55eac5e90>, 'target_153': <prophet.forecaster.Prophet object at 0x7cc55e539950>, 'target_154': <prophet.forecaster.Prophet object at 0x7cc55e419150>, 'target_155': <prophet.forecaster.Prophet object at 0x7cc55e539050>, 'target_156': <prophet.forecaster.Prophet object at 0x7cc55e27cdd0>, 'target_157': <prophet.forecaster.Prophet object at 0x7cc55e278e90>, 'target_158': <prophet.forecaster.Prophet object at 0x7cc55f014790>, 'target_159': <prophet.forecaster.Prophet object at 0x7cc55e4b9410>, 'target_160': <prophet.forecaster.Prophet object at 0x7cc55e184810>, 'target_161': <prophet.forecaster.Prophet object at 0x7cc55e1b0690>, 'target_162': <prophet.forecaster.Prophet object at 0x7cc55e188490>, 'target_163': <prophet.forecaster.Prophet object at 0x7cc55e172350>, 'target_164': <prophet.forecaster.Prophet object at 0x7cc55e043e10>, 'target_165': <prophet.forecaster.Prophet object at 0x7cc55e043e90>, 'target_166': <prophet.forecaster.Prophet object at 0x7cc55df63ed0>, 'target_167': <prophet.forecaster.Prophet object at 0x7cc55e0c75d0>, 'target_168': <prophet.forecaster.Prophet object at 0x7cc55df63110>, 'target_169': <prophet.forecaster.Prophet object at 0x7cc55e2b1010>, 'target_170': <prophet.forecaster.Prophet object at 0x7cc55e9be890>, 'target_171': <prophet.forecaster.Prophet object at 0x7cc55f6bc190>, 'target_172': <prophet.forecaster.Prophet object at 0x7cc55e567750>, 'target_173': <prophet.forecaster.Prophet object at 0x7cc55e32f850>, 'target_174': <prophet.forecaster.Prophet object at 0x7cc55de67050>, 'target_175': <prophet.forecaster.Prophet object at 0x7cc55eaed390>, 'target_176': <prophet.forecaster.Prophet object at 0x7cc55e617990>, 'target_177': <prophet.forecaster.Prophet object at 0x7cc55e3819d0>, 'target_178': <prophet.forecaster.Prophet object at 0x7cc55f015fd0>, 'target_179': <prophet.forecaster.Prophet object at 0x7cc55e06ba90>, 'target_180': <prophet.forecaster.Prophet object at 0x7cc55deb4610>, 'target_181': <prophet.forecaster.Prophet object at 0x7cc55f60b5d0>, 'target_182': <prophet.forecaster.Prophet object at 0x7cc55df58510>, 'target_183': <prophet.forecaster.Prophet object at 0x7cc595d6f090>, 'target_184': <prophet.forecaster.Prophet object at 0x7cc55e3b9290>, 'target_185': <prophet.forecaster.Prophet object at 0x7cc55e1f8e10>, 'target_186': <prophet.forecaster.Prophet object at 0x7cc55deec850>, 'target_187': <prophet.forecaster.Prophet object at 0x7cc55e14e8d0>, 'target_188': <prophet.forecaster.Prophet object at 0x7cc55dc23d90>, 'target_189': <prophet.forecaster.Prophet object at 0x7cc55df0bed0>, 'target_190': <prophet.forecaster.Prophet object at 0x7cc55e0d7050>, 'target_191': <prophet.forecaster.Prophet object at 0x7cc55e0a9d10>, 'target_192': <prophet.forecaster.Prophet object at 0x7cc55e390590>, 'target_193': <prophet.forecaster.Prophet object at 0x7cc55e0a84d0>, 'target_194': <prophet.forecaster.Prophet object at 0x7cc55db17710>, 'target_195': <prophet.forecaster.Prophet object at 0x7cc55e0c78d0>, 'target_196': <prophet.forecaster.Prophet object at 0x7cc55d9432d0>, 'target_197': <prophet.forecaster.Prophet object at 0x7cc55dbc3f50>, 'target_198': <prophet.forecaster.Prophet object at 0x7cc55de675d0>, 'target_199': <prophet.forecaster.Prophet object at 0x7cc55db97090>, 'target_200': <prophet.forecaster.Prophet object at 0x7cc55dcb0110>, 'target_201': <prophet.forecaster.Prophet object at 0x7cc55da7c1d0>, 'target_202': <prophet.forecaster.Prophet object at 0x7cc55dcb3ad0>, 'target_203': <prophet.forecaster.Prophet object at 0x7cc55da59190>, 'target_204': <prophet.forecaster.Prophet object at 0x7cc55dfb7490>, 'target_205': <prophet.forecaster.Prophet object at 0x7cc55da5f2d0>, 'target_206': <prophet.forecaster.Prophet object at 0x7cc55e4f4fd0>, 'target_207': <prophet.forecaster.Prophet object at 0x7cc55dffc950>, 'target_208': <prophet.forecaster.Prophet object at 0x7cc55e0d54d0>, 'target_209': <prophet.forecaster.Prophet object at 0x7cc55e172b10>, 'target_210': <prophet.forecaster.Prophet object at 0x7cc55e14e650>, 'target_211': <prophet.forecaster.Prophet object at 0x7cc55dedb850>, 'target_212': <prophet.forecaster.Prophet object at 0x7cc55de03510>, 'target_213': <prophet.forecaster.Prophet object at 0x7cc55dbd4e10>, 'target_214': <prophet.forecaster.Prophet object at 0x7cc55dbd4510>, 'target_215': <prophet.forecaster.Prophet object at 0x7cc55ddde650>, 'target_216': <prophet.forecaster.Prophet object at 0x7cc55dfe7950>, 'target_217': <prophet.forecaster.Prophet object at 0x7cc55d896050>, 'target_218': <prophet.forecaster.Prophet object at 0x7cc55d8a77d0>, 'target_219': <prophet.forecaster.Prophet object at 0x7cc55d8d74d0>, 'target_220': <prophet.forecaster.Prophet object at 0x7cc55d8a75d0>, 'target_221': <prophet.forecaster.Prophet object at 0x7cc55d8bd5d0>, 'target_222': <prophet.forecaster.Prophet object at 0x7cc55d71af10>, 'target_223': <prophet.forecaster.Prophet object at 0x7cc55db97a90>, 'target_224': <prophet.forecaster.Prophet object at 0x7cc55d916090>, 'target_225': <prophet.forecaster.Prophet object at 0x7cc55d9a45d0>, 'target_226': <prophet.forecaster.Prophet object at 0x7cc55d63a050>, 'target_227': <prophet.forecaster.Prophet object at 0x7cc55d7ddf90>, 'target_228': <prophet.forecaster.Prophet object at 0x7cc55d63ae90>, 'target_229': <prophet.forecaster.Prophet object at 0x7cc595db7ed0>, 'target_230': <prophet.forecaster.Prophet object at 0x7cc55db85fd0>, 'target_231': <prophet.forecaster.Prophet object at 0x7cc55d67ff50>, 'target_232': <prophet.forecaster.Prophet object at 0x7cc55daa4b10>, 'target_233': <prophet.forecaster.Prophet object at 0x7cc55d6d7e90>, 'target_234': <prophet.forecaster.Prophet object at 0x7cc55d86a410>, 'target_235': <prophet.forecaster.Prophet object at 0x7cc55d6122d0>, 'target_236': <prophet.forecaster.Prophet object at 0x7cc55d6116d0>, 'target_237': <prophet.forecaster.Prophet object at 0x7cc55d68d090>, 'target_238': <prophet.forecaster.Prophet object at 0x7cc55df7e8d0>, 'target_239': <prophet.forecaster.Prophet object at 0x7cc55db59fd0>, 'target_240': <prophet.forecaster.Prophet object at 0x7cc55d63be10>, 'target_241': <prophet.forecaster.Prophet object at 0x7cc55d7670d0>, 'target_242': <prophet.forecaster.Prophet object at 0x7cc55dad0e10>, 'target_243': <prophet.forecaster.Prophet object at 0x7cc55dedb610>, 'target_244': <prophet.forecaster.Prophet object at 0x7cc55db07650>, 'target_245': <prophet.forecaster.Prophet object at 0x7cc55da32310>, 'target_246': <prophet.forecaster.Prophet object at 0x7cc55d4f3e90>, 'target_247': <prophet.forecaster.Prophet object at 0x7cc55d44bd50>, 'target_248': <prophet.forecaster.Prophet object at 0x7cc55d38f4d0>, 'target_249': <prophet.forecaster.Prophet object at 0x7cc55d55ad90>, 'target_250': <prophet.forecaster.Prophet object at 0x7cc55d7dc090>, 'target_251': <prophet.forecaster.Prophet object at 0x7cc55d553950>, 'target_252': <prophet.forecaster.Prophet object at 0x7cc55d227b50>, 'target_253': <prophet.forecaster.Prophet object at 0x7cc55d20eb10>, 'target_254': <prophet.forecaster.Prophet object at 0x7cc55d226790>, 'target_255': <prophet.forecaster.Prophet object at 0x7cc55d2a5750>, 'target_256': <prophet.forecaster.Prophet object at 0x7cc55d1e8310>, 'target_257': <prophet.forecaster.Prophet object at 0x7cc55d18c7d0>, 'target_258': <prophet.forecaster.Prophet object at 0x7cc55d37d290>, 'target_259': <prophet.forecaster.Prophet object at 0x7cc55d1afdd0>, 'target_260': <prophet.forecaster.Prophet object at 0x7cc55d256690>, 'target_261': <prophet.forecaster.Prophet object at 0x7cc55d03c390>, 'target_262': <prophet.forecaster.Prophet object at 0x7cc55f1729d0>, 'target_263': <prophet.forecaster.Prophet object at 0x7cc55d047510>, 'target_264': <prophet.forecaster.Prophet object at 0x7cc55dc8b610>, 'target_265': <prophet.forecaster.Prophet object at 0x7cc55d0a3410>, 'target_266': <prophet.forecaster.Prophet object at 0x7cc55d357ed0>, 'target_267': <prophet.forecaster.Prophet object at 0x7cc55d356090>, 'target_268': <prophet.forecaster.Prophet object at 0x7cc55d093910>, 'target_269': <prophet.forecaster.Prophet object at 0x7cc55cf1f050>, 'target_270': <prophet.forecaster.Prophet object at 0x7cc55cfd8550>, 'target_271': <prophet.forecaster.Prophet object at 0x7cc55e7f3f50>, 'target_272': <prophet.forecaster.Prophet object at 0x7cc55cda56d0>, 'target_273': <prophet.forecaster.Prophet object at 0x7cc55dcdf5d0>, 'target_274': <prophet.forecaster.Prophet object at 0x7cc55cf8e250>, 'target_275': <prophet.forecaster.Prophet object at 0x7cc55cf8ddd0>, 'target_276': <prophet.forecaster.Prophet object at 0x7cc55d4ac890>, 'target_277': <prophet.forecaster.Prophet object at 0x7cc55d7eabd0>, 'target_278': <prophet.forecaster.Prophet object at 0x7cc55eedd290>, 'target_279': <prophet.forecaster.Prophet object at 0x7cc55d497f50>, 'target_280': <prophet.forecaster.Prophet object at 0x7cc55cf4b910>, 'target_281': <prophet.forecaster.Prophet object at 0x7cc55cf34210>, 'target_282': <prophet.forecaster.Prophet object at 0x7cc55d200750>, 'target_283': <prophet.forecaster.Prophet object at 0x7cc55d155c90>, 'target_284': <prophet.forecaster.Prophet object at 0x7cc55daf3d10>, 'target_285': <prophet.forecaster.Prophet object at 0x7cc55cee0750>, 'target_286': <prophet.forecaster.Prophet object at 0x7cc55cdb4ad0>, 'target_287': <prophet.forecaster.Prophet object at 0x7cc55cdd8990>, 'target_288': <prophet.forecaster.Prophet object at 0x7cc55cd80a10>, 'target_289': <prophet.forecaster.Prophet object at 0x7cc55cd84f90>, 'target_290': <prophet.forecaster.Prophet object at 0x7cc55cfe4410>, 'target_291': <prophet.forecas

In [10]:
# ----------------------------------------
# 予測モデルの推論用関数
# ----------------------------------------
def predict(
    test: pl.DataFrame,
    label_lags_1_batch: pl.DataFrame,
    label_lags_2_batch: pl.DataFrame,
    label_lags_3_batch: pl.DataFrame,
    label_lags_4_batch: pl.DataFrame,
) -> pl.DataFrame | pd.DataFrame:
    
    # この関数内では、予測に必要な情報だけを利用する
    # GrandTruthを使わない。train_labels.csvを直接参照しない
    
    X = test.to_pandas()
    date_id = X["date_id"].iloc[0]
    
    # 予測対象の日付を計算
    current_date = base_date + pd.to_timedelta(date_id, unit="D")
    
    preds = {}
    
    # 既存のProphetモデルを使用して予測値を生成
    for col in sel_cols:
        if col in prophet_models:
            # 予測したい日付のデータフレームを作成
            future_df = pd.DataFrame({"ds": [current_date]})
            
            # 事前学習したProphetモデルで予測を行う
            yhat = prophet_models[col].predict(future_df)["yhat"].iloc[0]
            preds[col] = yhat
        else:
            # モデルが存在しない場合はゼロを返す
            preds[col] = 0.0
            
    # DataFrameに変換して返す
    return pl.DataFrame(preds).select(pl.all().cast(pl.Float64))

# ========================
# RUN SERVER
# ========================
inference_server = kaggle_evaluation.mitsui_inference_server.MitsuiInferenceServer(predict)

if os.getenv("KAGGLE_IS_COMPETITION_RERUN"):
    inference_server.serve()
else:
    inference_server.run_local_gateway(("/kaggle/input/mitsui-commodity-prediction-challenge/",))