# Imports and Global Setup

In [1]:
pip_dir = "/kaggle/input/tabpfn-2-0-1-offline/"
!pip install --no-index --find-links=$pip_dir tabpfn

Looking in links: /kaggle/input/tabpfn-2-0-1-offline/
Processing /kaggle/input/tabpfn-2-0-1-offline/tabpfn-2.0.1-py3-none-any.whl
Requirement already satisfied: torch>=2.1 in /usr/local/lib/python3.11/dist-packages (from tabpfn) (2.6.0+cu124)
Requirement already satisfied: scikit-learn>=1 in /usr/local/lib/python3.11/dist-packages (from tabpfn) (1.2.2)
Requirement already satisfied: typing_extensions in /usr/local/lib/python3.11/dist-packages (from tabpfn) (4.15.0)
Requirement already satisfied: scipy in /usr/local/lib/python3.11/dist-packages (from tabpfn) (1.15.3)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from tabpfn) (2.2.3)
Requirement already satisfied: einops in /usr/local/lib/python3.11/dist-packages (from tabpfn) (0.8.1)
Requirement already satisfied: huggingface-hub in /usr/local/lib/python3.11/dist-packages (from tabpfn) (0.36.0)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.11/dist-packages (from scikit-learn>=1->tabpfn) (1.26.4)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from scikit-learn>=1->tabpfn) (1.5.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn>=1->tabpfn) (3.6.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from torch>=2.1->tabpfn) (3.20.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch>=2.1->tabpfn) (3.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch>=2.1->tabpfn) (3.1.6)
Requirement already satisfied: fsspec in /usr/local/lib/python3.11/dist-packages (from torch>=2.1->tabpfn) (2025.10.0)
Processing /kaggle/input/tabpfn-2-0-1-offline/nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (from torch>=2.1->tabpfn)
Processing /kaggle/input/tabpfn-2-0-1-offline/nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (from torch>=2.1->tabpfn)
Processing /kaggle/input/tabpfn-2-0-1-offline/nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (from torch>=2.1->tabpfn)
Processing /kaggle/input/tabpfn-2-0-1-offline/nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl (from torch>=2.1->tabpfn)
Processing /kaggle/input/tabpfn-2-0-1-offline/nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl (from torch>=2.1->tabpfn)
Processing /kaggle/input/tabpfn-2-0-1-offline/nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl (from torch>=2.1->tabpfn)
Processing /kaggle/input/tabpfn-2-0-1-offline/nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl (from torch>=2.1->tabpfn)
Processing /kaggle/input/tabpfn-2-0-1-offline/nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl (from torch>=2.1->tabpfn)
Processing /kaggle/input/tabpfn-2-0-1-offline/nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl (from torch>=2.1->tabpfn)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /usr/local/lib/python3.11/dist-packages (from torch>=2.1->tabpfn) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch>=2.1->tabpfn) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=2.1->tabpfn) (12.4.127)
Processing /kaggle/input/tabpfn-2-0-1-offline/nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (from torch>=2.1->tabpfn)
Requirement already satisfied: triton==3.2.0 in /usr/local/lib/python3.11/dist-packages (from torch>=2.1->tabpfn) (3.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch>=2.1->tabpfn) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch>=2.1->tabpfn) (1.3.0)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub->tabpfn) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub->tabpfn) (6.0.3)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from huggingface-hub->tabpfn) (2.32.5)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub->tabpfn) (4.67.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub->tabpfn) (1.2.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->tabpfn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->tabpfn) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->tabpfn) (2025.2)
Requirement already satisfied: mkl_fft in /usr/local/lib/python3.11/dist-packages (from numpy>=1.17.3->scikit-learn>=1->tabpfn) (1.3.8)
Requirement already satisfied: mkl_random in /usr/local/lib/python3.11/dist-packages (from numpy>=1.17.3->scikit-learn>=1->tabpfn) (1.2.4)
Requirement already satisfied: mkl_umath in /usr/local/lib/python3.11/dist-packages (from numpy>=1.17.3->scikit-learn>=1->tabpfn) (0.1.1)
Requirement already satisfied: mkl in /usr/local/lib/python3.11/dist-packages (from numpy>=1.17.3->scikit-learn>=1->tabpfn) (2025.3.0)
Requirement already satisfied: tbb4py in /usr/local/lib/python3.11/dist-packages (from numpy>=1.17.3->scikit-learn>=1->tabpfn) (2022.3.0)
Requirement already satisfied: mkl-service in /usr/local/lib/python3.11/dist-packages (from numpy>=1.17.3->scikit-learn>=1->tabpfn) (2.4.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas->tabpfn) (1.17.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch>=2.1->tabpfn) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub->tabpfn) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub->tabpfn) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub->tabpfn) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub->tabpfn) (2025.10.5)
Requirement already satisfied: onemkl-license==2025.3.0 in /usr/local/lib/python3.11/dist-packages (from mkl->numpy>=1.17.3->scikit-learn>=1->tabpfn) (2025.3.0)
Requirement already satisfied: intel-openmp<2026,>=2024 in /usr/local/lib/python3.11/dist-packages (from mkl->numpy>=1.17.3->scikit-learn>=1->tabpfn) (2024.2.0)
Requirement already satisfied: tbb==2022.* in /usr/local/lib/python3.11/dist-packages (from mkl->numpy>=1.17.3->scikit-learn>=1->tabpfn) (2022.3.0)
Requirement already satisfied: tcmlib==1.* in /usr/local/lib/python3.11/dist-packages (from tbb==2022.*->mkl->numpy>=1.17.3->scikit-learn>=1->tabpfn) (1.4.0)
Requirement already satisfied: intel-cmplr-lib-rt in /usr/local/lib/python3.11/dist-packages (from mkl_umath->numpy>=1.17.3->scikit-learn>=1->tabpfn) (2024.2.0)
Requirement already satisfied: intel-cmplr-lib-ur==2024.2.0 in /usr/local/lib/python3.11/dist-packages (from intel-openmp<2026,>=2024->mkl->numpy>=1.17.3->scikit-learn>=1->tabpfn) (2024.2.0)
Installing collected packages: nvidia-nvjitlink-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, nvidia-cusparse-cu12, nvidia-cudnn-cu12, nvidia-cusolver-cu12, tabpfn
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstalling nvidia-nvjitlink-cu12-12.5.82:
      Successfully uninstalled nvidia-nvjitlink-cu12-12.5.82
  Attempting uninstall: nvidia-curand-cu12
    Found existing installation: nvidia-curand-cu12 10.3.6.82
    Uninstalling nvidia-curand-cu12-10.3.6.82:
      Successfully uninstalled nvidia-curand-cu12-10.3.6.82
  Attempting uninstall: nvidia-cufft-cu12
    Found existing installation: nvidia-cufft-cu12 11.2.3.61
    Uninstalling nvidia-cufft-cu12-11.2.3.61:
      Successfully uninstalled nvidia-cufft-cu12-11.2.3.61
  Attempting uninstall: nvidia-cuda-runtime-cu12
    Found existing installation: nvidia-cuda-runtime-cu12 12.5.82
    Uninstalling nvidia-cuda-runtime-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-runtime-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-nvrtc-cu12
    Found existing installation: nvidia-cuda-nvrtc-cu12 12.5.82
    Uninstalling nvidia-cuda-nvrtc-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-nvrtc-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-cupti-cu12
    Found existing installation: nvidia-cuda-cupti-cu12 12.5.82
    Uninstalling nvidia-cuda-cupti-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-cupti-cu12-12.5.82
  Attempting uninstall: nvidia-cublas-cu12
    Found existing installation: nvidia-cublas-cu12 12.5.3.2
    Uninstalling nvidia-cublas-cu12-12.5.3.2:
      Successfully uninstalled nvidia-cublas-cu12-12.5.3.2
  Attempting uninstall: nvidia-cusparse-cu12
    Found existing installation: nvidia-cusparse-cu12 12.5.1.3
    Uninstalling nvidia-cusparse-cu12-12.5.1.3:
      Successfully uninstalled nvidia-cusparse-cu12-12.5.1.3
  Attempting uninstall: nvidia-cudnn-cu12
    Found existing installation: nvidia-cudnn-cu12 9.3.0.75
    Uninstalling nvidia-cudnn-cu12-9.3.0.75:
      Successfully uninstalled nvidia-cudnn-cu12-9.3.0.75
  Attempting uninstall: nvidia-cusolver-cu12
    Found existing installation: nvidia-cusolver-cu12 11.6.3.83
    Uninstalling nvidia-cusolver-cu12-11.6.3.83:
      Successfully uninstalled nvidia-cusolver-cu12-11.6.3.83
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
libcugraph-cu12 25.6.0 requires libraft-cu12==25.6.*, but you have libraft-cu12 25.2.0 which is incompatible.
pylibcugraph-cu12 25.6.0 requires pylibraft-cu12==25.6.*, but you have pylibraft-cu12 25.2.0 which is incompatible.
pylibcugraph-cu12 25.6.0 requires rmm-cu12==25.6.*, but you have rmm-cu12 25.2.0 which is incompatible.
Successfully installed nvidia-cublas-cu12-12.4.5.8 nvidia-cuda-cupti-cu12-12.4.127 nvidia-cuda-nvrtc-cu12-12.4.127 nvidia-cuda-runtime-cu12-12.4.127 nvidia-cudnn-cu12-9.1.0.70 nvidia-cufft-cu12-11.2.1.3 nvidia-curand-cu12-10.3.5.147 nvidia-cusolver-cu12-11.6.1.9 nvidia-cusparse-cu12-12.3.1.170 nvidia-nvjitlink-cu12-12.4.127 tabpfn-2.0.1

In [2]:
import os
import torch
import warnings
import numpy as np
import pandas as pd
from tabpfn import TabPFNRegressor
from sklearn.model_selection import KFold, GroupKFold
from sklearn.metrics import mean_squared_error

# Suppress all warnings
warnings.filterwarnings("ignore")

# Set a seed for reproducibility
np.random.seed(42)
torch.manual_seed(42)

TARGET = 'HOMELESS_RATE'

# Determine the device to use (GPU if available, otherwise CPU)
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f"Using device: {device}")

OFFLINE_MODEL_PATH = "/kaggle/input/tabpfn-2-0-1-offline/tabpfn-v2-regressor.ckpt"

Using device: cuda

# Data Loading

In [3]:
train_file = "/kaggle/input/california-homelessness-prediction-challenge/train.csv"
test_file = "/kaggle/input/california-homelessness-prediction-challenge/test.csv"

train_df = pd.read_csv(train_file)
test_df = pd.read_csv(test_file)
submission_df = pd.read_csv("/kaggle/input/california-homelessness-prediction-challenge/sample_submission.csv")

features = [col for col in train_df.columns if col != TARGET and col != 'ID']

X = train_df[features].values
y = train_df[TARGET].values
X_test = test_df[features].values

In [4]:
submission_df

        ID  HOMELESS_RATE
0    AL_13           1.23
1    LA_10           1.23
2    SD_15           1.23
3    SB_11           1.23
4    SB_09           1.23
5    OC_28           1.23
6    AL_02           1.23
7    RV_29           1.23
8    SB_01           1.23
9    SC_14           1.23
10   SB_41           1.23
11   AL_14           1.23
12   RV_02           1.23
13   SD_19           1.23
14   SB_36           1.23
15   SB_12           1.23
16   OC_29           1.23
17   AL_06           1.23
18   SB_23           1.23
19   OC_35           1.23
20   SC_12           1.23
21   RV_15           1.23
22   SF_07           1.23
23   SB_10           1.23
24   OC_18           1.23
25   OC_22           1.23
26   RV_19           1.23
27   SB_08           1.23
28   SB_24           1.23
29   LA_02           1.23
30   SB_29           1.23
31   SD_07           1.23
32   LA_15           1.23
33   OC_26           1.23
34   SD_09           1.23
35   SD_20           1.23
36   SB_06           1.23
37   OC_06           1.23
38   RV_26           1.23
39   RV_09           1.23
40   SB_34           1.23
41   OC_33           1.23
42   LA_09           1.23
43  SAC_02           1.23
44   OC_10           1.23
45   LA_01           1.23
46   SC_16           1.23
47   SD_04           1.23
48   SO_04           1.23
49   SO_09           1.23
50   AL_11           1.23
51   SD_01           1.23
52   SC_01           1.23
53   AL_03           1.23
54   RV_21           1.23
55   SB_25           1.23

# Model Training

In [5]:
# IDをアルファベットと、_ 数字に分けます

train_df_id_split = train_df['ID'].str.split('_', expand=True)
train_df['STATE'] = train_df_id_split[0]
train_df.drop('ID', axis = 1, inplace = True)
train_df

,HOMELESS_RATE,AGE_U18_PCT,AGE_18_24_PCT,AGE_25_34_PCT,AGE_35_44_PCT,AGE_45_54_PCT,AGE_55_59_PCT,AGE_60_61_PCT,AGE_62_64_PCT,AGE_65_69_PCT,...,DISABILITY_POP_PCT,NODISABILITY_POP_PCT,TOTAL_HOUSEHOLDS_PCT,FAMILY_HH_TOTAL,FAMILY_HH_CHILD_LT18_PCT,NONFAMILY_SINGLE_MALE_PCT,NONFAMILY_SINGLE_FEMALE_PCT,MULTI_PERSON_NONFAMILY_HH_PCT,INDIVIDUALS_NOT_IN_FAMILY_UNITS_PCT,STATE
0,0.000000,0.388210,0.054130,0.058164,0.061302,0.161269,0.062087,0.037431,0.051104,0.201053,...,0.460607,0.020397,0.305727,0.251373,0.076544,0.174829,0.054354,0.021966,0.054354,SC
1,0.000999,0.368737,0.089002,0.132744,0.137555,0.156465,0.082081,0.031715,0.035453,0.083043,...,0.457923,0.023203,0.227111,0.184183,0.064947,0.119236,0.042928,0.016283,0.042928,RV
2,0.004736,0.429991,0.071720,0.204073,0.176398,0.127522,0.046399,0.020886,0.025102,0.067669,...,0.517711,0.030974,0.237949,0.198297,0.094440,0.103857,0.039651,0.014248,0.039651,SC
3,0.001269,0.476342,0.058899,0.115471,0.156583,0.147944,0.064417,0.027537,0.032103,0.082117,...,0.498431,0.023747,0.272830,0.234998,0.118750,0.116247,0.037832,0.013240,0.037832,AL
4,0.000394,0.513634,0.078841,0.112881,0.145494,0.148405,0.066102,0.024644,0.029827,0.098252,...,0.485158,0.029264,0.249969,0.189581,0.093464,0.096118,0.060387,0.016156,0.060387,SAC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125,0.002657,0.409175,0.089357,0.166851,0.145895,0.128258,0.069670,0.029918,0.035483,0.090299,...,0.510729,0.031529,0.222504,0.154082,0.065876,0.088206,0.068421,0.021257,0.068421,AL
126,0.002084,0.540632,0.103225,0.136034,0.126443,0.120192,0.054043,0.027022,0.043790,0.092542,...,0.497139,0.031751,0.216901,0.130743,0.059997,0.070746,0.086158,0.022954,0.086158,RV
127,0.000396,0.262039,0.029467,0.072036,0.073173,0.083160,0.052606,0.033818,0.040789,0.164244,...,0.415653,0.011322,0.243746,0.206764,0.050035,0.156729,0.036982,0.015426,0.036982,OC
128,0.033858,0.357389,0.103374,0.202590,0.149430,0.125208,0.055579,0.022972,0.030457,0.083999,...,0.494994,0.027024,0.187579,0.116812,0.042014,0.074798,0.070767,0.025516,0.070767,LA
129,0.001528,0.547042,0.094976,0.126407,0.149050,0.123180,0.058079,0.020574,0.032266,0.075616,...,0.482083,0.032617,0.243039,0.189098,0.092774,0.096324,0.053941,0.016190,0.053941,RV

In [6]:
test_df_id_split = test_df['ID'].str.split('_', expand=True)
test_df['STATE'] = test_df_id_split[0]
test_df.drop('ID', axis = 1, inplace =True)
test_df

,AGE_U18_PCT,AGE_18_24_PCT,AGE_25_34_PCT,AGE_35_44_PCT,AGE_45_54_PCT,AGE_55_59_PCT,AGE_60_61_PCT,AGE_62_64_PCT,AGE_65_69_PCT,AGE_70_79_PCT,...,DISABILITY_POP_PCT,NODISABILITY_POP_PCT,TOTAL_HOUSEHOLDS_PCT,FAMILY_HH_TOTAL,FAMILY_HH_CHILD_LT18_PCT,NONFAMILY_SINGLE_MALE_PCT,NONFAMILY_SINGLE_FEMALE_PCT,MULTI_PERSON_NONFAMILY_HH_PCT,INDIVIDUALS_NOT_IN_FAMILY_UNITS_PCT,STATE
0,0.342169,0.088348,0.147178,0.134551,0.144855,0.073641,0.032186,0.036751,0.097467,0.157331,...,0.494866,0.019192,0.228051,0.161873,0.062935,0.098939,0.066178,0.022780,0.066178,AL
1,0.370642,0.090580,0.197082,0.152119,0.127954,0.060101,0.026158,0.032274,0.088054,0.103299,...,0.496151,0.025846,0.211684,0.121713,0.046176,0.075537,0.089971,0.030425,0.089971,LA
2,0.462069,0.074806,0.135474,0.148376,0.121019,0.064783,0.028337,0.037049,0.110785,0.140659,...,0.484905,0.040998,0.250991,0.191846,0.085025,0.106820,0.059145,0.018705,0.059145,SD
3,0.324003,0.070298,0.124383,0.123496,0.137429,0.089677,0.036605,0.056111,0.136795,0.175807,...,0.465484,0.023813,0.274098,0.193920,0.053325,0.140595,0.080177,0.022799,0.080177,SB
4,0.443576,0.091267,0.133863,0.124290,0.142770,0.074939,0.034057,0.045485,0.097654,0.117705,...,0.510769,0.028775,0.267414,0.216761,0.088704,0.128057,0.050654,0.020307,0.050654,SB
5,0.345233,0.081234,0.104020,0.105479,0.137022,0.087862,0.038239,0.062192,0.143134,0.202819,...,0.484538,0.017342,0.280499,0.231649,0.074469,0.157180,0.048850,0.010474,0.048850,OC
6,0.487742,0.064962,0.143756,0.170670,0.127228,0.062915,0.020173,0.028112,0.097568,0.122834,...,0.475009,0.033005,0.258501,0.203825,0.111050,0.092775,0.054676,0.010586,0.054676,AL
7,0.498786,0.086012,0.125515,0.126715,0.125975,0.062975,0.026369,0.035735,0.098126,0.151396,...,0.492707,0.030368,0.235513,0.184078,0.076372,0.107706,0.051436,0.016932,0.051436,RV
8,0.702073,0.099037,0.142570,0.136040,0.106274,0.044893,0.018610,0.023997,0.075148,0.052185,...,0.486777,0.053110,0.207542,0.116613,0.062714,0.053899,0.090929,0.024895,0.090929,SB
9,0.406645,0.049874,0.050471,0.116922,0.165461,0.086682,0.032312,0.044992,0.128407,0.203779,...,0.489639,0.010642,0.296291,0.272478,0.115306,0.157172,0.023813,0.006041,0.023813,SC
10,0.507030,0.106813,0.147147,0.131795,0.108047,0.059071,0.026415,0.032848,0.098916,0.115937,...,0.483991,0.035688,0.226308,0.165028,0.069022,0.096006,0.061280,0.020764,0.061280,SB
11,0.354978,0.078702,0.145036,0.150839,0.130769,0.066112,0.027952,0.044947,0.120450,0.147044,...,0.505499,0.027051,0.242382,0.195232,0.073481,0.121752,0.047149,0.017342,0.047149,AL
12,0.557241,0.100288,0.147299,0.146027,0.132378,0.058036,0.018918,0.025242,0.073172,0.075557,...,0.496821,0.038085,0.229124,0.169475,0.086231,0.083244,0.059648,0.019803,0.059648,RV
13,0.544585,0.112950,0.167257,0.084111,0.122896,0.051760,0.018928,0.032144,0.084730,0.121761,...,0.482190,0.039061,0.232405,0.168324,0.069794,0.098530,0.064081,0.027911,0.064081,SD
14,0.600205,0.106577,0.144240,0.143011,0.109404,0.047544,0.022564,0.024450,0.067870,0.088103,...,0.470719,0.036636,0.214045,0.133921,0.070512,0.063409,0.080124,0.021428,0.080124,SB
15,0.558359,0.110917,0.147463,0.148412,0.132607,0.053597,0.017996,0.022496,0.070727,0.072824,...,0.507388,0.034918,0.230098,0.158614,0.085152,0.073462,0.071484,0.024039,0.071484,SB
16,0.042803,0.012441,0.055502,0.029459,0.052537,0.042803,0.024109,0.072649,0.242635,0.593567,...,0.409334,0.000000,0.234642,0.201702,0.010121,0.191581,0.032940,0.007091,0.032940,OC
17,0.459433,0.059896,0.149636,0.169982,0.142704,0.062012,0.022977,0.032868,0.083629,0.104084,...,0.499185,0.028082,0.260543,0.220420,0.119010,0.101410,0.040123,0.013121,0.040123,AL
18,0.495670,0.125048,0.160460,0.125938,0.122306,0.057063,0.020761,0.028508,0.071594,0.102098,...,0.479143,0.024394,0.215767,0.136668,0.060070,0.076597,0.079099,0.020665,0.079099,SB
19,0.471155,0.073849,0.102384,0.128579,0.153085,0.079752,0.031887,0.038567,0.103262,0.144936,...,0.498921,0.029202,0.260928,0.218063,0.097359,0.120704,0.042865,0.015770,0.042865,OC
20,0.421330,0.093196,0.157986,0.146677,0.137333,0.063603,0.024629,0.031663,0.091168,0.111652,...,0.508113,0.027330,0.231795,0.172939,0.078749,0.094190,0.058855,0.020411,0.058855,SC
21,0.444623,0.109867,0.178370,0.150315,0.132239,0.047989,0.027058,0.026087,0.092817,0.080896,...,0.504949,0.026365,0.226026,0.144049,0.061407,0.082643,0.081977,0.024729,0.081977,RV
22,0.284698,0.093321,0.182055,0.127850,0.123496,0.063477,0.026004,0.036259,0.121411,0.176878,...,0.478945,0.018117,0.222840,0.178387,0.067145,0.111242,0.044453,0.013211,0.044453,SF
23,0.489480,0.110451,0.156670,0.129233,0.123016,0.062220,0.019273,0.025114,0.098197,0.103400,...,0.495713,0.029040,0.232110,0.143500,0.065410,0.078090,0.088610,0.030954,0.088610,SB
24,0.316107,0.079987,0.159228,0.124567,0.125379,0.076651,0.030404,0.034518,0.107395,0.190388,...,0.488962,0.017193,0.250779,0.201404,0.067983,0.133421,0.049375,0.015306,0.049375,OC
25,0.430804,0.089004,0.131696,0.109118,0.151746,0.067786,0.030850,0.035856,0.097123,0.139967,...,0.491830,0.024243,0.233050,0.164604,0.071178,0.093426,0.068446,0.022007,0.068446,OC
26,0.373258,0.077009,0.118269,0.078771,0.115450,0.071435,0.034116,0.043598,0.143896,0.290098,...,0.525034,0.024858,0.269372,0.213313,0.048691,0.164622,0.056059,0.019477,0.056059,RV
27,0.469111,0.080764,0.160796,0.152057,0.136067,0.065122,0.024301,0.031880,0.089525,0.097453,...,0.463942,0.036542,0.231098,0.172237,0.079401,0.092836,0.058861,0.020090,0.058861,SB
28,0.394304,0.040823,0.124684,0.125000,0.146835,0.097468,0.031646,0.043354,0.094304,0.224684,...,0.531962,0.042089,0.231962,0.164873,0.057595,0.107278,0.067089,0.022785,0.067089,SB
29,0.355285,0.086547,0.200502,0.154236,0.136475,0.060707,0.026269,0.033830,0.085532,0.100810,...,0.488350,0.024152,0.216273,0.142507,0.055849,0.086658,0.073766,0.023487,0.073766,LA
30,0.453519,0.083425,0.159460,0.126849,0.140204,0.067437,0.023389,0.040339,0.099155,0.111199,...,0.483594,0.035668,0.253320,0.185328,0.076384,0.108944,0.067992,0.022410,0.067992,SB
31,0.467587,0.091294,0.157350,0.137628,0.119413,0.065280,0.023847,0.033750,0.092070,0.108880,...,0.496666,0.036478,0.225611,0.153486,0.069045,0.084441,0.072126,0.025852,0.072126,SD
32,0.507757,0.094025,0.153366,0.138183,0.129772,0.058281,0.021687,0.031768,0.077270,0.104547,...,0.487291,0.035401,0.225281,0.133471,0.060353,0.073118,0.091811,0.027730,0.091811,LA
33,0.284941,0.040419,0.066390,0.090266,0.144478,0.086032,0.036840,0.053165,0.174596,0.340201,...,0.513706,0.014055,0.265735,0.233348,0.061196,0.172152,0.032388,0.013575,0.032388,OC
34,0.429288,0.080961,0.190361,0.146408,0.112189,0.050746,0.023387,0.032107,0.095983,0.116937,...,0.454991,0.035554,0.231492,0.160485,0.072731,0.087754,0.071007,0.017338,0.071007,SD
35,0.488142,0.132335,0.125061,0.139487,0.102384,0.051711,0.021822,0.037408,0.094377,0.146455,...,0.454401,0.031479,0.229829,0.154645,0.065587,0.089059,0.075183,0.010269,0.075183,SD
36,0.494095,0.126870,0.146434,0.160880,0.132381,0.040742,0.026295,0.027043,0.066446,0.082822,...,0.499410,0.032042,0.231617,0.160329,0.071721,0.088608,0.071288,0.024091,0.071288,SB
37,0.441850,0.096046,0.157873,0.124752,0.139457,0.070476,0.026561,0.032562,0.093956,0.092839,...,0.507893,0.029355,0.239035,0.167838,0.073053,0.094785,0.071197,0.028291,0.071197,OC
38,0.513577,0.069347,0.146438,0.123947,0.112969,0.059456,0.024526,0.035132,0.093691,0.157608,...,0.495961,0.036713,0.240381,0.187503,0.080718,0.106785,0.052879,0.015249,0.052879,RV
39,0.497192,0.079572,0.133050,0.110911,0.102165,0.054302,0.023370,0.033860,0.116538,0.183947,...,0.482461,0.029356,0.230734,0.151915,0.065103,0.086812,0.078819,0.022748,0.078819,RV
40,0.451669,0.177431,0.203846,0.118868,0.082075,0.047460,0.015820,0.032003,0.069086,0.103628,...,0.369956,0.059942,0.255080,0.173295,0.065965,0.107329,0.081785,0.025907,0.081785,SB
41,0.432873,0.067233,0.106743,0.113602,0.147044,0.073970,0.030415,0.046946,0.116522,0.180820,...,0.506691,0.025169,0.262729,0.224770,0.083232,0.141538,0.037959,0.009976,0.037959,OC
42,0.540369,0.152858,0.156746,0.132484,0.122375,0.050663,0.017918,0.024695,0.058287,0.058606,...,0.505182,0.032386,0.183118,0.086914,0.043782,0.043133,0.096203,0.033729,0.096203,LA
43,0.400193,0.087182,0.171356,0.130801,0.114281,0.066199,0.023303,0.036989,0.111065,0.144717,...,0.487342,0.025283,0.236702,0.162670,0.059646,0.103024,0.074032,0.021705,0.074032,SAC
44,0.472290,0.093220,0.132219,0.136152,0.131972,0.069566,0.020637,0.036230,0.090944,0.123717,...,0.489205,0.027604,0.244347,0.183423,0.086270,0.097153,0.060924,0.019385,0.060924,OC
45,0.376951,0.093127,0.206520,0.154319,0.124468,0.055051,0.020934,0.028666,0.087569,0.101038,...,0.507498,0.024174,0.209783,0.118163,0.044274,0.073890,0.091620,0.035206,0.091620,LA
46,0.407488,0.120233,0.126530,0.113497,0.136225,0.071797,0.027528,0.030587,0.116662,0.138245,...,0.501601,0.025402,0.230011,0.186628,0.078506,0.108122,0.043383,0.014610,0.043383,SC
47,0.344996,0.167469,0.117821,0.108876,0.113852,0.055788,0.022125,0.033399,0.108400,0.158260,...,0.372201,0.015508,0.246335,0.211348,0.073043,0.138305,0.034987,0.006934,0.034987,SD
48,0.349430,0.115777,0.162268,0.139097,0.117951,0.067037,0.030069,0.043416,0.099130,0.133773,...,0.472256,0.042816,0.218506,0.156119,0.060288,0.095831,0.062388,0.016197,0.062388,SO
49,0.417411,0.085691,0.137148,0.147259,0.130078,0.061541,0.024266,0.035223,0.112910,0.146907,...,0.485622,0.023351,0.235165,0.167495,0.068462,0.099033,0.067670,0.025214,0.067670,SO
50,0.539557,0.041125,0.064869,0.128662,0.178479,0.052863,0.011558,0.021414,0.136189,0.233133,...,0.502374,0.023743,0.272287,0.247648,0.128214,0.119434,0.024639,0.008064,0.024639,AL
51,0.378172,0.109509,0.188190,0.145327,0.120944,0.056693,0.021233,0.031443,0.088560,0.121069,...,0.482353,0.026710,0.221929,0.165905,0.068114,0.097791,0.056024,0.016654,0.056024,SD
52,0.444278,0.060877,0.138937,0.166843,0.118292,0.084184,0.027545,0.031653,0.074623,0.107491,...,0.489600,0.029767,0.254412,0.193096,0.083693,0.109403,0.061316,0.020671,0.061316,SC
53,0.243193,0.242740,0.171397,0.107287,0.099238,0.050262,0.020027,0.028167,0.099040,0.158817,...,0.487927,0.017679,0.175211,0.137842,0.052148,0.085694,0.037369,0.011715,0.037369,AL
54,0.219564,0.061993,0.103410,0.085260,0.140593,0.099628,0.045508,0.055991,0.189020,0.279583,...,0.592362,0.016238,0.220920,0.171446,0.030914,0.140532,0.049475,0.017718,0.049475,RV
55,0.608138,0.139872,0.146838,0.123839,0.121849,0.049757,0.013877,0.011002,0.082707,0.056723,...,0.536654,0.035493,0.191674,0.108801,0.055451,0.053350,0.082873,0.041851,0.082873,SB

In [7]:
%%time

test_predictions = []
oof_predictions = np.zeros(len(X))

n_splits = 10

gkf = GroupKFold(n_splits=n_splits)

print(f"Starting {n_splits}-fold cross-validation...")

for fold, (train_index, val_index) in enumerate(gkf.split(X, y, groups=train_df['STATE'])):

    X_train, X_val = X[train_index], X[val_index]
    y_train, y_val = y[train_index], y[val_index]

    model = TabPFNRegressor(device=device, ignore_pretraining_limits=True, model_path=OFFLINE_MODEL_PATH)
    model.fit(X_train,y_train)

    val_preds = model.predict(X_val)
    oof_predictions[val_index] = val_preds
    mse = mean_squared_error(y_val, val_preds)

    print(f"MSE score on validation set for Fold {fold+1}: {mse}")

    test_preds = model.predict(X_test)
    test_predictions.append(test_preds)


# oof_df = pd.DataFrame({'ID': train_df['ID'], TARGET: oof_predictions})
# oof_df.to_csv('oof.csv', index=False)

submission_df[TARGET] = np.mean(test_predictions, axis=0)

submission_df.to_csv('submission.csv', index=False)
submission_df.head()

Starting 10-fold cross-validation...
MSE score on validation set for Fold 1: 6.773067864422496e-06
MSE score on validation set for Fold 2: 1.2205203763285029e-05
MSE score on validation set for Fold 3: 8.635678225078815e-06
MSE score on validation set for Fold 4: 1.0800655481663945e-05
MSE score on validation set for Fold 5: 2.6386453279543855e-05
MSE score on validation set for Fold 6: 0.00029492688815358295
MSE score on validation set for Fold 7: 8.031199708009469e-05
MSE score on validation set for Fold 8: 9.141616923929884e-06
MSE score on validation set for Fold 9: 5.2170017777878836e-05
MSE score on validation set for Fold 10: 1.750996934610539e-05
CPU times: user 14.9 s, sys: 843 ms, total: 15.8 s
Wall time: 15.7 s

      ID  HOMELESS_RATE
0  AL_13       0.003558
1  LA_10       0.012699
2  SD_15       0.001488
3  SB_11       0.002642
4  SB_09       0.001163