In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

import spacy

# doc2vecを使うためのライブラリ
from gensim.models.doc2vec import Doc2Vec, TaggedDocument

import lightgbm as lgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error


# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/learning-agency-lab-automated-essay-scoring-2/sample_submission.csv
/kaggle/input/learning-agency-lab-automated-essay-scoring-2/train.csv
/kaggle/input/learning-agency-lab-automated-essay-scoring-2/test.csv

In [2]:
# データの読み込み
train_df = pd.read_csv('/kaggle/input/learning-agency-lab-automated-essay-scoring-2/train.csv')
test_df = pd.read_csv('/kaggle/input/learning-agency-lab-automated-essay-scoring-2/test.csv')

submission_df = pd.read_csv('/kaggle/input/learning-agency-lab-automated-essay-scoring-2/sample_submission.csv')


# データの確認
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17307 entries, 0 to 17306
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   essay_id   17307 non-null  object
 1   full_text  17307 non-null  object
 2   score      17307 non-null  int64
dtypes: int64(1), object(2)
memory usage: 405.8+ KB

In [3]:
train_df.head()

  essay_id                                          full_text  score
0  000d118  Many people have car where they live. The thin...      3
1  000fe60  I am a scientist at NASA that is discussing th...      3
2  001ab80  People always wish they had the same technolog...      4
3  001bdc0  We all heard about Venus, the planet without a...      4
4  002ba53  Dear, State Senator\n\nThis is a letter to arg...      3

In [4]:
train_df.head(2).full_text.values

array(['Many people have car where they live. The thing they don\'t know is that when you use a car alot of thing can happen\xa0like you can get in accidet or\xa0the smoke that the car has is bad to breath\xa0on if someone is walk but in VAUBAN,Germany they dont have that proble because 70 percent of vauban\'s families do not own cars,and 57 percent sold a car to move there. Street parkig ,driveways and home garages are forbidden\xa0on the outskirts of freiburd that near the French and Swiss borders. You probaly won\'t see a car in Vauban\'s streets because they are completely "car free" but\xa0If some that lives in VAUBAN that owns a car ownership is allowed,but there are only two places that you can park a large garages at the edge of the development,where a car owner buys a space but it not cheap to buy one they sell the space for you car for $40,000 along with a home. The vauban people completed this in 2006 ,they said that this an example of a growing trend in Europe,The untile states and some where else are suburban life from auto use this is called "smart planning". The current efforts to drastically reduce greenhouse gas emissions from tailes the passengee cars are responsible for 12 percent of greenhouse gas emissions in Europe and up to 50 percent in some car intensive in the United States. I honeslty think that good idea that they did that is Vaudan because that makes cities denser and better for walking and in VAUBAN there are 5,500 residents within a rectangular square mile. In the artical David Gold berg said that "All of our development since World war 2 has been centered on the cars,and that will have to change" and i think that was very true what David Gold said because alot thing we need cars to do we can go anyway were with out cars beacuse some people are a very lazy to walk to place thats why they alot of people use car and i think that it was a good idea that that they did that in VAUBAN so people can see how we really don\'t need car to go to place from place because we can walk from were we need to go or we can ride bycles with out the use of a car. It good that they are doing that if you thik about your help the earth in way and thats a very good thing to. In the United states ,the Environmental protection Agency is promoting what is called "car reduced"communtunties,and the legislators are starting to act,if cautiously. Maany experts expect pubic transport serving suburbs to play a much larger role in a new six years federal transportation bill to approved this year. In previous bill,80 percent of appropriations have by law gone to highways and only 20 percent to other transports. There many good reason why they should do this.    ',
       'I am a scientist at NASA that is discussing the "face" on mars. I will be explaining how the "face" is a land form. By sharing my information about this isue i will tell you just that.\n\nFirst off, how could it be a martions drawing. There is no plant life on mars as of rite now that we know of, which means so far as we know it is not possible for any type of life. That explains how it could not be made by martians. Also why and how would a martion build a face so big. It just does not make any since that a martian did this.\n\nNext, why it is a landform. There are many landforms that are weird here in America, and there is also landforms all around the whole Earth. Many of them look like something we can relate to like a snake a turtle a human... So if there are landforms on earth dont you think landforms are on mars to? Of course! why not? It\'s just unique that the landform on Mars looks like a human face. Also if there was martians and they were trying to get our attention dont you think we would have saw one by now?\n\nFinaly, why you should listen to me. You should listen to me because i am a member of NASA and i\'ve been dealing with all of this stuff that were talking about and people who say martians did this have no relation with NASA and have never worked with anything to relate to this landform. One last thing is that everyone working at NASA says the same thing i say, that the "face" is just a landform.\n\nTo sum all this up the "face" on mars is a landform but others would like to beleive it\'s a martian sculpture. Which every one that works at NASA says it\'s a landform and they are all the ones working on the planet and taking pictures.'],
      dtype=object)

In [5]:
train_df.head(2).score.values

array([3, 3])

In [6]:
#シンプルにDec2Vecを使ってみる
# データの前処理
nlp = spacy.load('en_core_web_sm')

# テキストの前処理
def preprocess_text(text):
    doc = nlp(text)
    return [token.lemma_ for token in doc if not token.is_stop]

In [7]:
# テキストの前処理

train_df['full_text_'] = train_df['full_text'].apply(preprocess_text)

In [8]:
train_df.tail(2)

,essay_id,full_text,score,full_text_
17305,fffb49b,"In ""The Challenge of Exporing Venus,"" the auth...",1,"["", challenge, Exporing, Venus, ,, "", author, ..."
17306,fffed3e,Venus is worthy place to study but dangerous. ...,2,"[Venus, worthy, place, study, dangerous, ., re..."

In [9]:
full_text_series = train_df['full_text_']

full_text_series[:2]

0    [people, car, live, ., thing, know, use, car, ...
1    [scientist, NASA, discuss, ", face, ", mar, .,...
Name: full_text_, dtype: object

In [10]:
tagged_data = [TaggedDocument(words=doc, tags=[i]) for i, doc in enumerate(full_text_series)]

In [11]:
len(tagged_data) == len(train_df)

True

In [12]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

In [13]:
# モデルの学習
model = Doc2Vec(vector_size=300, window=5, min_count=1, workers=4)

In [14]:

model.build_vocab(tagged_data)

In [15]:

model.train(tagged_data, total_examples=model.corpus_count, epochs=100)

In [16]:
# ベクトルの取得

vectors_ = [model.infer_vector(doc) for doc in full_text_series]

vectors_[:2]

[array([-3.67572188e-01, -5.81442833e-01, -5.37984431e-01, -1.97785354e+00,
        -2.58478075e-01,  1.08138120e+00,  1.71891725e+00, -8.94088328e-01,
        -1.25482416e+00, -1.23267233e+00,  1.31274194e-01,  1.82513773e-01,
        -1.55877090e+00,  1.09710775e-01, -3.78429517e-02, -1.00583065e+00,
         8.31118822e-02, -7.92860091e-01, -3.87062758e-01, -1.39483488e+00,
        -9.07627225e-01, -7.44669497e-01,  2.87938744e-01, -9.77331579e-01,
        -3.30037981e-01, -6.67116344e-01, -1.76833856e+00,  1.41257262e+00,
         1.53115427e+00,  7.81967282e-01, -3.49227399e-01, -2.31198460e-01,
         4.66660380e-01, -7.93569386e-01,  9.94111225e-02, -1.12662446e+00,
         2.26989341e+00,  5.42326212e-01,  1.47476411e+00, -1.13304520e+00,
         3.68145376e-01,  6.58291280e-01, -2.69858146e+00, -2.16137301e-02,
        -5.93902409e-01, -3.07373941e-01,  1.33315277e+00, -6.29561186e-01,
         5.58357894e-01,  6.25317752e-01,  7.65040755e-01, -7.17988133e-01,
         1.43394694e-01, -3.26996267e-01,  7.76128531e-01, -1.28496861e+00,
         6.12883866e-02,  2.71789956e+00,  1.00082052e+00,  5.23616254e-01,
        -1.60247579e-01, -4.96490508e-01,  7.84942687e-01, -8.03510189e-01,
        -2.28515342e-01, -9.03855205e-01, -1.53039858e-01, -5.05957752e-02,
        -6.37984455e-01, -3.64365667e-01, -1.28524756e+00, -2.11561844e-01,
         1.25441939e-01, -3.79599839e-01, -1.23859584e+00, -1.38719186e-01,
        -1.57558906e+00, -1.16197988e-01, -1.11087573e+00,  4.11078572e-01,
        -1.02804732e+00,  1.01218677e+00,  1.23596168e+00,  2.40362358e+00,
        -1.41255426e+00,  9.85328972e-01,  1.29539251e+00,  9.57583249e-01,
         1.79009899e-01,  1.06963789e+00,  2.63016939e-01,  1.49640834e+00,
        -8.32802296e-01,  5.28997958e-01,  1.33662832e+00,  6.04654193e-01,
         2.25126553e+00, -2.49728918e-01, -9.51734722e-01, -1.49144089e+00,
        -6.45820677e-01, -3.06350708e-01, -1.15312076e+00,  4.34959769e-01,
        -3.47143948e-01,  7.17400193e-01,  8.08950245e-01,  9.21154082e-01,
         6.92170560e-02, -2.09296092e-01,  3.87652129e-01, -1.38696027e+00,
         1.82985103e+00,  2.50731468e+00,  6.50277853e-01,  5.96604109e-01,
        -4.20729935e-01, -8.30850005e-01,  1.69255793e+00, -5.05235314e-01,
         5.47922432e-01,  2.28808808e+00,  4.56113040e-01,  9.25254107e-01,
        -4.66152310e-01, -2.10390821e-01,  8.51460516e-01, -2.09390551e-01,
        -6.63057029e-01,  5.18020540e-02,  7.19737858e-02, -3.27940315e-01,
        -8.78618062e-01, -1.35097373e+00, -4.13692780e-02,  1.06732965e+00,
        -1.64452255e-01, -1.32492483e-01, -2.20293641e+00,  3.53258252e-01,
         8.44728231e-01, -3.56286705e-01, -7.89741576e-01,  4.88171518e-01,
        -7.15041578e-01,  9.64430720e-02,  1.01398565e-02, -1.08848989e-01,
         1.19588983e+00, -1.39189541e+00,  1.20016992e+00, -2.59395599e+00,
        -2.58397162e-01, -5.26857257e-01, -1.86912909e-01,  2.29179072e+00,
        -1.08439076e+00, -1.58271515e+00,  5.72371900e-01, -4.49257165e-01,
        -7.41345465e-01,  6.21557534e-01, -1.39420664e+00,  1.30827710e-01,
         3.41287404e-01, -5.75181067e-01, -4.00391966e-01, -1.33777392e+00,
        -6.18111808e-03,  1.86915481e+00,  2.62725711e-01, -2.48620939e+00,
         8.57385933e-01,  7.84688950e-01,  1.61830044e+00,  7.54233301e-01,
        -3.70756209e-01, -1.68996191e+00,  9.79242921e-01, -1.90845236e-01,
         1.11706853e+00, -1.18742657e+00, -2.92735457e+00, -2.72999078e-01,
        -4.49391901e-01, -3.85670125e-01, -8.84738326e-01,  2.31029320e+00,
         8.37198019e-01, -1.84025180e+00,  1.27754879e+00,  5.82852006e-01,
         9.95298699e-02,  1.29826558e+00, -1.69329032e-01,  4.89240944e-01,
        -3.22593190e-02, -1.43074775e+00,  2.17241979e+00, -7.36225545e-01,
        -2.60154188e-01, -5.62978506e-01,  6.87739193e-01, -6.62065744e-01,
         5.98561093e-02, -1.36823070e+00, -5.17316222e-01, -1.52837366e-01,
        -8.99670087e-03,  1.89657748e+00,  1.55670837e-01, -6.73800826e-01,
        -1.45602870e+00,  1.40268421e+00,  4.14868802e-01, -1.04012132e+00,
        -1.13997614e+00, -1.42586625e+00, -2.30395722e+00,  4.54990089e-01,
        -5.08701980e-01,  1.43867230e+00,  1.80237859e-01, -8.83137941e-01,
         1.33823931e-01,  1.16937494e+00,  1.09326434e+00, -4.58944440e-01,
        -6.36362493e-01, -1.47551537e+00, -9.83215421e-02,  1.22799486e-01,
        -2.42467627e-01,  1.15347505e+00, -1.60130286e+00, -1.03297126e+00,
        -6.19905032e-02,  3.62464637e-01,  3.87766302e-01,  8.16341698e-01,
        -6.20838165e-01,  5.97769976e-01, -6.95828497e-01, -6.25071466e-01,
         4.75691766e-01,  8.26952159e-01, -8.64889443e-01,  5.27593553e-01,
        -2.31717259e-01, -8.31112564e-01, -1.29246652e+00,  1.07120132e+00,
         1.14348125e+00,  2.05382302e-01, -5.01621246e-01,  9.08620119e-01,
         6.43749058e-01,  1.95840132e+00,  4.40207869e-01,  1.14591396e+00,
         6.06776812e-05, -3.09538186e-01,  1.45163685e-01, -3.79754156e-01,
        -1.96378779e+00,  7.19458759e-02, -5.39142042e-02, -1.40027654e+00,
        -3.63566667e-01,  2.21585348e-01, -2.97297984e-01,  1.44638157e+00,
        -3.98126930e-01, -7.62307405e-01, -2.52606571e-01,  8.19318175e-01,
        -1.19732410e-01,  1.24853477e-01, -8.92823488e-02, -6.35833293e-02,
        -8.36992562e-02,  2.04659745e-01,  9.21561360e-01, -9.47485268e-01,
        -3.48387629e-01,  1.47964656e+00, -6.09284341e-01,  1.24614263e+00,
         1.52033079e+00,  3.30103844e-01,  5.99585176e-01,  3.04814875e-01,
        -6.89198256e-01,  5.20914435e-01, -2.95613974e-01, -1.91185549e-01,
        -1.51013374e+00, -1.65179086e+00, -4.81998235e-01,  6.94153070e-01],
       dtype=float32),
 array([-1.5849324 ,  0.62356347, -0.57155156, -0.00712427, -0.17793839,
        -1.6180295 , -0.45815817,  0.66263884, -0.2505003 , -0.6536852 ,
        -0.55824244,  0.19679506, -0.47892082, -0.0477823 , -1.0030773 ,
        -0.9204692 ,  1.6705478 ,  1.1917938 , -0.51543707, -1.3437892 ,
         1.53308   , -0.09088954, -0.3771816 , -0.40022284,  0.3491023 ,
        -2.019075  ,  0.38630065, -0.08293934, -0.46522823,  0.52204806,
        -0.19771704,  2.4783957 ,  1.1900028 , -0.77646804, -0.343326  ,
         0.89236265, -0.520583  ,  1.0371876 ,  2.2144775 , -2.4325945 ,
         0.6493439 ,  1.4219424 , -0.14072968, -0.991242  ,  0.13153267,
         1.4250056 ,  0.27804902,  1.0372534 ,  0.03323821, -0.55933005,
         1.7792423 ,  0.75856   , -1.1197393 , -0.14242272,  0.881075  ,
        -2.4363623 , -0.9879131 ,  0.36268649, -0.10452261, -0.49261916,
         0.27820617,  0.86288756,  0.8828609 ,  0.5755686 , -0.5625039 ,
        -1.7436733 ,  1.071949  , -1.4442054 , -0.03098128, -0.12842727,
         0.02511557, -1.7184103 ,  0.23655279,  0.3829995 , -0.9985743 ,
         1.1659425 ,  1.2439065 ,  1.639772  , -0.510552  ,  1.9378853 ,
        -0.54686624, -2.2947788 , -0.15039313, -0.6512358 , -1.3371466 ,
         0.17196172, -0.46230057, -1.2831932 , -1.687885  ,  2.9726467 ,
        -0.70001996,  0.9780909 ,  0.24337691,  0.13155715,  0.30593896,
         0.7979262 ,  0.39747325,  2.174042  ,  0.6888895 ,  1.6715821 ,
         1.0642216 , -1.1007291 ,  0.39719436, -0.16386954,  0.17588566,
        -1.6540815 ,  0.47499382,  0.0413897 , -1.2864416 ,  0.00381381,
        -0.12738498,  0.46762255,  0.9917397 ,  1.1462294 ,  2.0575883 ,
         0.0966718 , -1.0876503 ,  2.8622217 ,  0.38226247,  1.6335001 ,
         0.38618985,  0.8769797 ,  0.539     ,  0.8317605 ,  0.02012267,
         0.17615655, -1.3897126 ,  1.498422  , -0.8119359 , -0.24800132,
        -0.80288935,  0.8501983 ,  0.15377066,  1.7752455 ,  0.87827826,
         2.2484279 ,  1.3167939 ,  2.0462556 , -1.8890704 , -1.6376625 ,
        -2.357846  , -0.9897134 , -1.344775  , -1.327229  ,  0.20838447,
         1.0010023 , -0.7417966 , -0.42966643, -1.2418848 ,  0.18639109,
         0.42962027, -0.07901751, -0.33162084,  0.30622613, -2.221141  ,
         0.4599093 , -1.2920821 , -1.2448852 , -0.24830472, -1.0026382 ,
        -0.34003904, -2.081674  ,  1.6090568 , -0.7076918 ,  0.0590596 ,
        -0.29689655, -1.3396493 ,  2.5221412 ,  0.05021781,  0.31308538,
        -0.06865434,  0.24320062,  1.4929423 , -0.04190633, -0.30606058,
         0.43054247, -0.4082121 , -0.22593954, -0.11905908,  1.7205557 ,
         1.1526062 ,  0.9572918 ,  1.569801  , -0.6744572 ,  1.2171712 ,
         0.05884677,  0.03045174,  0.40093124, -0.46118698, -0.9416608 ,
         0.10917059,  1.8102553 ,  1.3780813 ,  0.50975984, -0.21951215,
         0.59694684,  0.17546077,  0.6517421 , -0.6224455 , -1.2744355 ,
        -1.990188  ,  0.0615555 , -0.3725806 , -1.94541   ,  0.9305011 ,
         0.524213  ,  1.1867896 , -1.489292  ,  0.22431208, -2.4472744 ,
        -2.0043764 , -0.61761916,  0.77652   ,  0.50250405,  0.2734705 ,
        -2.4766936 ,  1.3624566 ,  2.482748  , -0.78013605,  0.4039598 ,
         0.1063339 , -1.5283339 ,  0.5441879 , -1.5837817 , -0.24198827,
        -1.4354788 , -0.3659764 , -0.6389708 , -1.5412639 , -0.80366856,
         1.5568794 ,  0.99793285, -0.47285226, -1.0015789 , -0.06454528,
        -0.78258455, -1.0070294 , -1.8201084 ,  0.45906472, -1.1527604 ,
         1.4157196 , -1.3136191 ,  0.5805154 , -1.4889368 ,  1.3044609 ,
        -0.1581553 , -0.32741103,  0.32924113, -0.6704532 ,  2.0055692 ,
         0.05921409, -1.040673  ,  1.1388495 ,  0.81407785, -0.12629053,
        -0.14852908,  1.4810336 ,  1.1275096 , -0.9310821 ,  0.9700577 ,
         1.1659305 ,  0.93571377,  0.03712413,  0.75117606,  2.1199565 ,
         0.5685831 ,  0.9864064 ,  1.3532417 ,  0.1449136 ,  0.6814893 ,
         0.2114281 ,  0.91871506, -0.8970186 , -0.68514484,  0.25877258,
         0.14643756,  1.1642814 , -0.27863133,  1.6465933 ,  1.242959  ,
        -0.57561666,  0.76947844, -0.6411327 ,  0.11024404, -0.6529361 ,
         0.2878473 ,  2.2245064 ,  1.6048273 ,  0.46573523,  1.6327164 ,
        -0.04976441,  1.2875721 , -0.86824393,  0.00717058,  1.6333867 ,
        -0.7146615 , -0.5943536 ,  0.58855903,  0.4259806 , -0.5950666 ],
       dtype=float32)]

In [17]:

vectors = np.array(vectors_)
vectors[:2]

array([[-3.67572188e-01, -5.81442833e-01, -5.37984431e-01,
        -1.97785354e+00, -2.58478075e-01,  1.08138120e+00,
         1.71891725e+00, -8.94088328e-01, -1.25482416e+00,
        -1.23267233e+00,  1.31274194e-01,  1.82513773e-01,
        -1.55877090e+00,  1.09710775e-01, -3.78429517e-02,
        -1.00583065e+00,  8.31118822e-02, -7.92860091e-01,
        -3.87062758e-01, -1.39483488e+00, -9.07627225e-01,
        -7.44669497e-01,  2.87938744e-01, -9.77331579e-01,
        -3.30037981e-01, -6.67116344e-01, -1.76833856e+00,
         1.41257262e+00,  1.53115427e+00,  7.81967282e-01,
        -3.49227399e-01, -2.31198460e-01,  4.66660380e-01,
        -7.93569386e-01,  9.94111225e-02, -1.12662446e+00,
         2.26989341e+00,  5.42326212e-01,  1.47476411e+00,
        -1.13304520e+00,  3.68145376e-01,  6.58291280e-01,
        -2.69858146e+00, -2.16137301e-02, -5.93902409e-01,
        -3.07373941e-01,  1.33315277e+00, -6.29561186e-01,
         5.58357894e-01,  6.25317752e-01,  7.65040755e-01,
        -7.17988133e-01,  1.43394694e-01, -3.26996267e-01,
         7.76128531e-01, -1.28496861e+00,  6.12883866e-02,
         2.71789956e+00,  1.00082052e+00,  5.23616254e-01,
        -1.60247579e-01, -4.96490508e-01,  7.84942687e-01,
        -8.03510189e-01, -2.28515342e-01, -9.03855205e-01,
        -1.53039858e-01, -5.05957752e-02, -6.37984455e-01,
        -3.64365667e-01, -1.28524756e+00, -2.11561844e-01,
         1.25441939e-01, -3.79599839e-01, -1.23859584e+00,
        -1.38719186e-01, -1.57558906e+00, -1.16197988e-01,
        -1.11087573e+00,  4.11078572e-01, -1.02804732e+00,
         1.01218677e+00,  1.23596168e+00,  2.40362358e+00,
        -1.41255426e+00,  9.85328972e-01,  1.29539251e+00,
         9.57583249e-01,  1.79009899e-01,  1.06963789e+00,
         2.63016939e-01,  1.49640834e+00, -8.32802296e-01,
         5.28997958e-01,  1.33662832e+00,  6.04654193e-01,
         2.25126553e+00, -2.49728918e-01, -9.51734722e-01,
        -1.49144089e+00, -6.45820677e-01, -3.06350708e-01,
        -1.15312076e+00,  4.34959769e-01, -3.47143948e-01,
         7.17400193e-01,  8.08950245e-01,  9.21154082e-01,
         6.92170560e-02, -2.09296092e-01,  3.87652129e-01,
        -1.38696027e+00,  1.82985103e+00,  2.50731468e+00,
         6.50277853e-01,  5.96604109e-01, -4.20729935e-01,
        -8.30850005e-01,  1.69255793e+00, -5.05235314e-01,
         5.47922432e-01,  2.28808808e+00,  4.56113040e-01,
         9.25254107e-01, -4.66152310e-01, -2.10390821e-01,
         8.51460516e-01, -2.09390551e-01, -6.63057029e-01,
         5.18020540e-02,  7.19737858e-02, -3.27940315e-01,
        -8.78618062e-01, -1.35097373e+00, -4.13692780e-02,
         1.06732965e+00, -1.64452255e-01, -1.32492483e-01,
        -2.20293641e+00,  3.53258252e-01,  8.44728231e-01,
        -3.56286705e-01, -7.89741576e-01,  4.88171518e-01,
        -7.15041578e-01,  9.64430720e-02,  1.01398565e-02,
        -1.08848989e-01,  1.19588983e+00, -1.39189541e+00,
         1.20016992e+00, -2.59395599e+00, -2.58397162e-01,
        -5.26857257e-01, -1.86912909e-01,  2.29179072e+00,
        -1.08439076e+00, -1.58271515e+00,  5.72371900e-01,
        -4.49257165e-01, -7.41345465e-01,  6.21557534e-01,
        -1.39420664e+00,  1.30827710e-01,  3.41287404e-01,
        -5.75181067e-01, -4.00391966e-01, -1.33777392e+00,
        -6.18111808e-03,  1.86915481e+00,  2.62725711e-01,
        -2.48620939e+00,  8.57385933e-01,  7.84688950e-01,
         1.61830044e+00,  7.54233301e-01, -3.70756209e-01,
        -1.68996191e+00,  9.79242921e-01, -1.90845236e-01,
         1.11706853e+00, -1.18742657e+00, -2.92735457e+00,
        -2.72999078e-01, -4.49391901e-01, -3.85670125e-01,
        -8.84738326e-01,  2.31029320e+00,  8.37198019e-01,
        -1.84025180e+00,  1.27754879e+00,  5.82852006e-01,
         9.95298699e-02,  1.29826558e+00, -1.69329032e-01,
         4.89240944e-01, -3.22593190e-02, -1.43074775e+00,
         2.17241979e+00, -7.36225545e-01, -2.60154188e-01,
        -5.62978506e-01,  6.87739193e-01, -6.62065744e-01,
         5.98561093e-02, -1.36823070e+00, -5.17316222e-01,
        -1.52837366e-01, -8.99670087e-03,  1.89657748e+00,
         1.55670837e-01, -6.73800826e-01, -1.45602870e+00,
         1.40268421e+00,  4.14868802e-01, -1.04012132e+00,
        -1.13997614e+00, -1.42586625e+00, -2.30395722e+00,
         4.54990089e-01, -5.08701980e-01,  1.43867230e+00,
         1.80237859e-01, -8.83137941e-01,  1.33823931e-01,
         1.16937494e+00,  1.09326434e+00, -4.58944440e-01,
        -6.36362493e-01, -1.47551537e+00, -9.83215421e-02,
         1.22799486e-01, -2.42467627e-01,  1.15347505e+00,
        -1.60130286e+00, -1.03297126e+00, -6.19905032e-02,
         3.62464637e-01,  3.87766302e-01,  8.16341698e-01,
        -6.20838165e-01,  5.97769976e-01, -6.95828497e-01,
        -6.25071466e-01,  4.75691766e-01,  8.26952159e-01,
        -8.64889443e-01,  5.27593553e-01, -2.31717259e-01,
        -8.31112564e-01, -1.29246652e+00,  1.07120132e+00,
         1.14348125e+00,  2.05382302e-01, -5.01621246e-01,
         9.08620119e-01,  6.43749058e-01,  1.95840132e+00,
         4.40207869e-01,  1.14591396e+00,  6.06776812e-05,
        -3.09538186e-01,  1.45163685e-01, -3.79754156e-01,
        -1.96378779e+00,  7.19458759e-02, -5.39142042e-02,
        -1.40027654e+00, -3.63566667e-01,  2.21585348e-01,
        -2.97297984e-01,  1.44638157e+00, -3.98126930e-01,
        -7.62307405e-01, -2.52606571e-01,  8.19318175e-01,
        -1.19732410e-01,  1.24853477e-01, -8.92823488e-02,
        -6.35833293e-02, -8.36992562e-02,  2.04659745e-01,
         9.21561360e-01, -9.47485268e-01, -3.48387629e-01,
         1.47964656e+00, -6.09284341e-01,  1.24614263e+00,
         1.52033079e+00,  3.30103844e-01,  5.99585176e-01,
         3.04814875e-01, -6.89198256e-01,  5.20914435e-01,
        -2.95613974e-01, -1.91185549e-01, -1.51013374e+00,
        -1.65179086e+00, -4.81998235e-01,  6.94153070e-01],
       [-1.58493245e+00,  6.23563468e-01, -5.71551561e-01,
        -7.12426705e-03, -1.77938387e-01, -1.61802948e+00,
        -4.58158165e-01,  6.62638843e-01, -2.50500292e-01,
        -6.53685212e-01, -5.58242440e-01,  1.96795061e-01,
        -4.78920817e-01, -4.77822982e-02, -1.00307727e+00,
        -9.20469224e-01,  1.67054784e+00,  1.19179380e+00,
        -5.15437067e-01, -1.34378922e+00,  1.53307998e+00,
        -9.08895433e-02, -3.77181590e-01, -4.00222838e-01,
         3.49102288e-01, -2.01907492e+00,  3.86300653e-01,
        -8.29393417e-02, -4.65228230e-01,  5.22048056e-01,
        -1.97717041e-01,  2.47839570e+00,  1.19000280e+00,
        -7.76468039e-01, -3.43326002e-01,  8.92362654e-01,
        -5.20582974e-01,  1.03718758e+00,  2.21447754e+00,
        -2.43259454e+00,  6.49343908e-01,  1.42194235e+00,
        -1.40729681e-01, -9.91241992e-01,  1.31532669e-01,
         1.42500556e+00,  2.78049022e-01,  1.03725338e+00,
         3.32382061e-02, -5.59330046e-01,  1.77924228e+00,
         7.58560002e-01, -1.11973929e+00, -1.42422721e-01,
         8.81075025e-01, -2.43636227e+00, -9.87913072e-01,
         3.62686485e-01, -1.04522608e-01, -4.92619157e-01,
         2.78206170e-01,  8.62887561e-01,  8.82860899e-01,
         5.75568616e-01, -5.62503874e-01, -1.74367332e+00,
         1.07194901e+00, -1.44420540e+00, -3.09812799e-02,
        -1.28427267e-01,  2.51155663e-02, -1.71841025e+00,
         2.36552790e-01,  3.82999510e-01, -9.98574317e-01,
         1.16594255e+00,  1.24390650e+00,  1.63977206e+00,
        -5.10551989e-01,  1.93788528e+00, -5.46866238e-01,
        -2.29477882e+00, -1.50393128e-01, -6.51235819e-01,
        -1.33714664e+00,  1.71961725e-01, -4.62300569e-01,
        -1.28319323e+00, -1.68788505e+00,  2.97264671e+00,
        -7.00019956e-01,  9.78090882e-01,  2.43376911e-01,
         1.31557152e-01,  3.05938959e-01,  7.97926188e-01,
         3.97473246e-01,  2.17404199e+00,  6.88889503e-01,
         1.67158210e+00,  1.06422162e+00, -1.10072911e+00,
         3.97194356e-01, -1.63869545e-01,  1.75885662e-01,
        -1.65408146e+00,  4.74993825e-01,  4.13896963e-02,
        -1.28644156e+00,  3.81380739e-03, -1.27384976e-01,
         4.67622548e-01,  9.91739690e-01,  1.14622939e+00,
         2.05758834e+00,  9.66717973e-02, -1.08765030e+00,
         2.86222172e+00,  3.82262468e-01,  1.63350010e+00,
         3.86189848e-01,  8.76979709e-01,  5.38999975e-01,
         8.31760526e-01,  2.01226659e-02,  1.76156551e-01,
        -1.38971257e+00,  1.49842203e+00, -8.11935902e-01,
        -2.48001322e-01, -8.02889347e-01,  8.50198328e-01,
         1.53770655e-01,  1.77524555e+00,  8.78278255e-01,
         2.24842787e+00,  1.31679392e+00,  2.04625559e+00,
        -1.88907039e+00, -1.63766253e+00, -2.35784602e+00,
        -9.89713371e-01, -1.34477496e+00, -1.32722902e+00,
         2.08384469e-01,  1.00100231e+00, -7.41796613e-01,
        -4.29666430e-01, -1.24188483e+00,  1.86391085e-01,
         4.29620266e-01, -7.90175125e-02, -3.31620842e-01,
         3.06226134e-01, -2.22114110e+00,  4.59909290e-01,
        -1.29208207e+00, -1.24488521e+00, -2.48304725e-01,
        -1.00263822e+00, -3.40039045e-01, -2.08167410e+00,
         1.60905683e+00, -7.07691789e-01,  5.90595976e-02,
        -2.96896547e-01, -1.33964932e+00,  2.52214122e+00,
         5.02178147e-02,  3.13085377e-01, -6.86543360e-02,
         2.43200615e-01,  1.49294233e+00, -4.19063307e-02,
        -3.06060582e-01,  4.30542469e-01, -4.08212095e-01,
        -2.25939542e-01, -1.19059078e-01,  1.72055566e+00,
         1.15260625e+00,  9.57291782e-01,  1.56980097e+00,
        -6.74457192e-01,  1.21717119e+00,  5.88467680e-02,
         3.04517392e-02,  4.00931239e-01, -4.61186975e-01,
        -9.41660821e-01,  1.09170593e-01,  1.81025529e+00,
         1.37808132e+00,  5.09759843e-01, -2.19512150e-01,
         5.96946836e-01,  1.75460771e-01,  6.51742101e-01,
        -6.22445524e-01, -1.27443552e+00, -1.99018800e+00,
         6.15555011e-02, -3.72580588e-01, -1.94541001e+00,
         9.30501103e-01,  5.24213016e-01,  1.18678963e+00,
        -1.48929203e+00,  2.24312082e-01, -2.44727445e+00,
        -2.00437641e+00, -6.17619157e-01,  7.76520014e-01,
         5.02504051e-01,  2.73470491e-01, -2.47669363e+00,
         1.36245656e+00,  2.48274803e+00, -7.80136049e-01,
         4.03959811e-01,  1.06333904e-01, -1.52833390e+00,
         5.44187903e-01, -1.58378172e+00, -2.41988271e-01,
        -1.43547881e+00, -3.65976393e-01, -6.38970792e-01,
        -1.54126394e+00, -8.03668559e-01,  1.55687940e+00,
         9.97932851e-01, -4.72852260e-01, -1.00157893e+00,
        -6.45452812e-02, -7.82584548e-01, -1.00702941e+00,
        -1.82010841e+00,  4.59064722e-01, -1.15276039e+00,
         1.41571963e+00, -1.31361914e+00,  5.80515385e-01,
        -1.48893678e+00,  1.30446088e+00, -1.58155307e-01,
        -3.27411026e-01,  3.29241127e-01, -6.70453191e-01,
         2.00556922e+00,  5.92140891e-02, -1.04067302e+00,
         1.13884950e+00,  8.14077854e-01, -1.26290530e-01,
        -1.48529083e-01,  1.48103356e+00,  1.12750959e+00,
        -9.31082129e-01,  9.70057726e-01,  1.16593051e+00,
         9.35713768e-01,  3.71241309e-02,  7.51176059e-01,
         2.11995649e+00,  5.68583071e-01,  9.86406386e-01,
         1.35324168e+00,  1.44913599e-01,  6.81489289e-01,
         2.11428106e-01,  9.18715060e-01, -8.97018611e-01,
        -6.85144842e-01,  2.58772582e-01,  1.46437556e-01,
         1.16428137e+00, -2.78631330e-01,  1.64659333e+00,
         1.24295902e+00, -5.75616658e-01,  7.69478440e-01,
        -6.41132712e-01,  1.10244036e-01, -6.52936101e-01,
         2.87847310e-01,  2.22450638e+00,  1.60482728e+00,
         4.65735227e-01,  1.63271642e+00, -4.97644134e-02,
         1.28757215e+00, -8.68243933e-01,  7.17057521e-03,
         1.63338673e+00, -7.14661479e-01, -5.94353616e-01,
         5.88559031e-01,  4.25980598e-01, -5.95066607e-01]], dtype=float32)

In [18]:

vectors.shape

(17307, 300)

In [19]:
# データの分割

X = vectors

y = train_df['score']

In [20]:
# yの値が１～６なので、LihgtGBMのクラスに合わせて、０～５に並べ替えるために書き換える

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

y_ = le.fit_transform(y)

In [21]:
print(y_.min())
print(y_.max())

0
5

In [22]:
print(X.shape)
print(y_.shape)

(17307, 300)
(17307,)

In [23]:
y_.dtype

dtype('int64')

In [24]:

X_train, X_valid, y_train, y_valid = train_test_split(X, y_, test_size=0.2, random_state=0)

# y_　は０～５の６クラス

In [25]:
# モデルの学習

lgb_train = lgb.Dataset(X_train, y_train)

lgb_valid = lgb.Dataset(X_valid, y_valid, reference=lgb_train)

params = {
    'objective': 'multiclass', # 多クラス分類
    'num_class': 6, # クラスの数
    'metric': 'multi_logloss' # 損失関数にmulti_loglossを使用
}

lgb_model = lgb.train(params, lgb_train, valid_sets=lgb_valid, num_boost_round=1000,
                     #  early_stopping_rounds=10
                     )

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.062043 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 76500
[LightGBM] [Info] Number of data points in the train set: 13845, number of used features: 300
[LightGBM] [Info] Start training from score -2.619956
[LightGBM] [Info] Start training from score -1.300584
[LightGBM] [Info] Start training from score -1.011908
[LightGBM] [Info] Start training from score -1.477036
[LightGBM] [Info] Start training from score -2.911614
[LightGBM] [Info] Start training from score -4.756556
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

In [26]:
# モデルの評価

y_pred = lgb_model.predict(X_valid)

y_pred

array([[2.52988300e-04, 5.44516252e-01, 4.54062233e-01, 1.16852380e-03,
        6.83443409e-11, 2.66777842e-09],
       [4.19151742e-06, 9.89917476e-01, 1.00543889e-02, 2.39423480e-05,
        7.18783240e-14, 8.47005872e-10],
       [1.27747488e-05, 6.14014413e-02, 8.34814240e-01, 1.03770999e-01,
        4.57595095e-07, 8.72131836e-08],
       ...,
       [2.26518580e-06, 5.14822627e-04, 9.87161363e-01, 1.23061139e-02,
        8.96096262e-06, 6.47385234e-06],
       [4.47718696e-04, 3.94147004e-01, 6.00498873e-01, 4.90630987e-03,
        3.25409129e-08, 6.27079446e-08],
       [8.75687148e-02, 8.92558106e-01, 1.98723385e-02, 8.40412781e-07,
        5.31912511e-14, 7.10106233e-11]])

In [27]:
# 予測値をクラスに変換
y_pred = np.argmax(y_pred, axis=1)

mean_squared_error(y_valid, y_pred)

0.6285384170999422

In [28]:
test_df['full_text'] = test_df['full_text'].apply(preprocess_text)

In [29]:
test_full_text_series = test_df['full_text']

test_full_text_series[:3]

0    [people, car, live, ., thing, know, use, car, ...
1    [scientist, NASA, discuss, ", face, ", mar, .,...
2    [People, wish, technology, see, movie, ,, good...
Name: full_text, dtype: object

In [30]:
tagged_data_test = [TaggedDocument(words=doc, tags=[i]) for i, doc in enumerate(test_full_text_series)]

In [31]:
model.train(tagged_data_test, total_examples=model.corpus_count, epochs=100)

In [32]:
# ベクトルの取得

vectors_test_ = [model.infer_vector(doc) for doc in test_full_text_series]

In [33]:
vectors_test = np.array(vectors_test_)

In [34]:
vectors_test.shape

(3, 300)

In [35]:
prediction = lgb_model.predict(vectors_test)

In [36]:
print(prediction.max(), prediction.min())

0.9997450998052889 8.197388488064299e-20

In [37]:
# inversする
predict = np.argmax(prediction, axis=1)
predict

array([0, 1, 1])

In [38]:
# ラベルをinversする
Y_pre =le.inverse_transform(predict)
Y_pre

array([1, 2, 2])

In [39]:
submission_df['score'] =Y_pre
submission_df

  essay_id  score
0  000d118      1
1  000fe60      2
2  001ab80      2

In [40]:
submission_df.to_csv('/kaggle/working/submission.csv', index=False)